### ISSUE TITLE
Closure dependency injection broken on `visible()` and `hidden()` for text columns

### ISSUE THREAD

**Issue by josefbehr** [laravel-filament/filament#7757] opened 2023-08-14 21:27 UTC
### Package

filament/filament

### Package Version

v3.0.21

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.2.6

### Problem description

I created a table column that should be hidden if a certain condition, depending on model parameters, is met. To this end, I added closure customization with the `hidden()` method on the column like this
```php
                Tables\Columns\TextColumn::make('name'),
                    ->hidden(static fn (User $record) => $record->name !== 'test@example.com'),
```

This results in a fatal error, since `$record` is `null`. This does not work for any of the closure parameters. It's always null. Does work fine for other methods like `timezone()` or `description()`.

![image](https://github.com/filamentphp/filament/assets/4368880/ef1a2d14-75af-43c0-a793-efa57de388d6)

### Expected behavior

I expected the current `$record` (or any other supported parameter) to be injected.

### Steps to reproduce

Without the reproduction repo:

1. Fresh laravel project
2. Install filament v3
3. Create a resource (e.g. UserResource)
4. Add a single column to the resource's table
5. Try to conditionally hide the column using `->hidden(fn (Model $record): bool => true))`

With reproduction repo:

1. Clone the repo
2. Copy .env.example to .env and set a database path (e.g. sqlite)
3. Migrate and populate the database (`php artisan migrate` and `php artisan db:seed`)
4. Log in to the admin panel at `/admin` using user `test@example.com` with password `password`
5. Try to access to user resource

### Reproduction repository

https://github.com/josefbehr/filament-closure-dependecy-injection-bug-reproduction

**Comment by awcodes** [comment] 2023-08-15 11:43
This isn't a bug. You can't conditionally show or hide a table column based on the record. Html tables don't work that way. It's impossible to have one row with a column and one row without that column.

**Comment by lbanchio** [comment] 2023-08-15 14:43
@awcodes, 
You are right, in a traditional table layout, it doesn't make sense to hide/show columns based on the record. However, in a stacked or split layout, it can be useful.

Maybe it would be a good idea to add some functionality related to the visibility of the record (like using CSS), so that other fields can make better use of that free space.

Indeed, there is [an interesting issue](https://github.com/filamentphp/filament/issues/7111) that hasn't had any updates, but it seems to be heading in the same direction.

**Comment by awcodes** [comment] 2023-08-15 14:46
Fair enough. interesting issue indeed.

**Comment by danharrin** [comment] 2023-08-16 21:37
Dupe of #7111

**Closed as not planned by danharrin** 2023-08-16 21:37 UTC
Labels: bug, unconfirmed

**Comment by orbitsdev** [comment] 2023-10-21 13:45
where is the solution sir?

**Comment by NaungYeHtet** [comment] 2023-10-25 14:14
How about record filter with tabs, those tabs make tables looks separate

**Comment by erasdev** [comment] 2023-12-08 19:46
If you want to conditionally display a specific row's value for a column, you could just return an empty string from the column table component using `formatStateUsing`. The column would still exist, but would not show value for rows meeting condition.

```
    Tables\Columns\TextColumn::make('name'),
         ->formatStateUsing(fn($state) => condition ? $state : ' ')
```

If you want the entire column to be conditional, build your array of column components before returning from the table function of your resource. Provided you can locate correct model instance to do your conditional check without relying on dependency injection.

```
public static function table(Table $table): Table
{
    $columns = [
        Tables\Columns\TextColumn::make('name'),
        Tables\Columns\TextColumn::make('slug'),
         //etc.
    ];

    if(condition){
        //modify $columns;
    }

    return $table
        ->columns($columns);
           //etc.
}
```

**Comment by kayy-kim** [comment] 2025-09-20 06:23
https://filamentphp.com/docs/4.x/tables/columns/overview#column-utility-injection

what is this then :(

**Comment by danharrin** [comment] 2025-09-22 07:40
> https://filamentphp.com/docs/4.x/tables/columns/overview#column-utility-injection

Bad example that was copied from the "infolist entries" utility injection section where it does work.

I have changed it here d11e375cfceca3348015e1d8d52c8fb069904439
