### ISSUE TITLE
When using HasManyRepeater in a HasManyRepeater, it duplicated x times x when saving

### ISSUE THREAD

**Issue by Robinvm** [laravel-filament/filament#2203] opened 2022-04-23 10:17 UTC
### Package

filament/forms

### Package Version

2.11

### Laravel Version

9.9

### Livewire Version

2.10

### PHP Version

8.1

### Bug description

When using HasManyRepeater in a HasManyRepeater, it duplicated x times x when saving.

It duplicates weirdly, but easy to reproduce to see the error.

`HasManyRepeater::make('productExtras')
                    ->relationship('productExtras')
                    ->schema([
                        TextInput::make('name')
                            ->label('Naam')
                            ->required()
                            ->maxLength(255)
                            ->rules([
                                'required',
                                'max:255',
                            ]),
                        Toggle::make('required')
                            ->label('Verplicht'),
                        Select::make('type')
                            ->label('Naam')
                            ->options([
                                'single' => '1 optie',
                                'multiple' => 'Meerdere opties (mogelijk nog niet ondersteund door jouw webshop)',
                            ])
                            ->default('single')
                            ->required()
                            ->rules([
                                'required',
                            ]),
                        HasManyRepeater::make('productExtraOptions')
                            ->relationship('productExtraOptions')
                            ->schema([
                                TextInput::make('value')
                                    ->label('Waarde')
                                    ->required()
                                    ->maxLength(255)
                                    ->rules([
                                        'required',
                                        'max:255',
                                    ]),
                                TextInput::make('price')
                                    ->label('Meerprijs van deze optie')
                                    ->prefix('€')
                                    ->helperText('Voorbeeld: 10.25')
                                    ->rules([
                                        'numeric',
                                        'min:0.00',
                                        'max:10000',
                                    ]),
                                Toggle::make('calculate_only_1_quantity')
                                    ->label('Deze extra maar 1x meetellen, ook al worden er meerdere van het product gekocht'),
                            ]),
                    ]),`

**Comment by danharrin** [comment] 2022-04-24 11:08
Duplicate of #2074

**Closed by danharrin** 2022-04-24 11:08 UTC
Labels: bug, unconfirmed

**Comment by danharrin** [comment] 2022-04-24 19:06
Hey, can you report back if #2216 fixes this?
