### ISSUE TITLE
Table filter indicators not showing in grid mode

### ISSUE THREAD

**Issue by romaldyminaya** [laravel-filament/filament#5055] opened 2022-11-24 15:35 UTC
### Package

filament/tables

### Package Version

 v2.16.51

### Laravel Version

v9.40.1

### Livewire Version

v2.10.7  

### PHP Version

8.1.2

### Problem description

When using filters in table with the new grid system, the appled filters doesn't show up as they do when filtering in normal table view.

Show example:

Normal table:
![image](https://user-images.githubusercontent.com/2809147/203814528-836860b0-8fb9-49d7-8dc9-cfbc0a8774db.png)

Grid table:
![image](https://user-images.githubusercontent.com/2809147/203814890-fb60ee41-03a0-4ff3-98b4-8a98af50cb7f.png)

As you may notice, the the filters are applied btu the section where they should be showed doesn't say anything.

### Expected behavior

When the filters are applied the counter should show how many filters are being used and display them in the upper secition of the table:

### Steps to reproduce

There's an example in the author's resource in the reproduction repository.
  
 ```
 public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Grid::make(6)
                    ->schema([
                        Stack::make([
                            TextColumn::make('subject')
                                ->label(__('filament-core::labels.subject'))
                                ->searchable(['subject', 'body'])
                                ->alignLeft(),
                            TagsColumn::make('to')
                                ->separator(','),
                        ])->alignLeft()
                            ->columnSpan(4),
                        Stack::make([
                            TextColumn::make('created_at')
                                ->label(__('filament-core::labels.created_at'))
                                ->date('d.m.Y')
                                ->alignRight(),
                            TextColumn::make('created_at')
                                ->label(__('filament-core::labels.created_at'))
                                ->time('H:i A')
                                ->alignRight(),
                        ])->alignRight()
                            ->columnSpan(2),
                    ]),
            ])
            ->filters([
                Filter::make('to')
                    ->form([
                        TagsInput::make('to')
                            ->label(__('filament-core::labels.email_to'))
                            ->separator(','),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['to'],
                                function (Builder $query, $to): Builder {

                                    foreach ($to as $email) {
                                        $query->orWhere('to', 'like', '%' . Str::lower($email) . '%');
                                    }

                                    return $query;
                                }
                            );
                    }),
                Filter::make('created_at')
                    ->label('filament-core::labels.created_at')
                    ->form([
                        DatePicker::make('created_from')
                            ->label(__('filament-core::labels.created_from')),
                        DatePicker::make('created_until')
                            ->label(__('filament-core::labels.created_until')),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '<=', $date),
                            );
                    })
            ])
            ->actions([
                DeleteAction::make(),
            ])
            ->bulkActions([
                DeleteBulkAction::make(),
            ]);
    }
```

### Reproduction repository

https://github.com/romaldyminaya/demo

**Comment by awcodes** [comment] 2022-11-27 15:28
Since you are using a custom filter you need to specific what the indicators are on your filter with `->indicateUsing()`.

Relevant docs can be found at [https://filamentphp.com/docs/2.x/tables/filters#custom-indicators](https://filamentphp.com/docs/2.x/tables/filters#custom-indicators)

Closing as this is not a bug and using the appropriate method in your demo produces the desired results.

**Closed as completed by awcodes** 2022-11-27 15:28 UTC
Labels: bug, unconfirmed

**Comment by romaldyminaya** [comment] 2022-11-29 12:02
Thank you @awcodes ,

Crisp and clear.
