### ISSUE TITLE
ToggleColumn flickers if toggling between null and non-null value

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#7226] opened 2023-07-26 15:11 UTC
### Package

filament/filament

### Package Version

* v3.0.0-beta11

### Laravel Version

* v10.16.1 

### Livewire Version

* v3.0.0-beta.4

### PHP Version

* 8.2.7

### Problem description

When you use `ToggleColumn` to toggle between a `null` and a non`null` value, the toggle input flickers.

### Expected behavior

The toggle should not flicker.

### Steps to reproduce

Just add this to a newly created `UserResource`
```php
Tables\Columns\ToggleColumn::make('email_verified_at')
    ->updateStateUsing(function ($state, $record) {
        $record->email_verified_at = $state ? now() : null;
        $record->save();

        return $state;
    }),
```

### Reproduction repository

https://github.com/mokhosh/filament-v3-bug-reproduction

**Comment by zepfietje** [comment] 2023-07-26 15:47
Please provide more details like a screen recording to explain what you mean with the toggle flickering. Since the disabled styling is applied when the toggle state gets pushed to the back end, that could be the flicker.

I'll reopen the issue if it really is a bug and you provide more evidence of that.
Thanks. 🙂

**Comment by mokhosh** [comment] 2023-07-26 19:03
You can add screen recordings to the long list of required parameters for new issues 😄 

No, it's not the disabled state, that's actually a very good feedback. It's flicker:

https://github.com/filamentphp/filament/assets/6499685/e2e960f9-57d4-486f-8f5d-3a78cef80190

**Comment by mokhosh** [comment] 2023-07-26 19:04
I've also done the reproduction repository btw which should be easy to check.

**Comment by zepfietje** [comment] 2023-07-27 07:49
> I've also done the reproduction repository btw which should be easy to check.

Yeah thanks, though I wanted to be sure what you meant exactly.
It's clear to me now and seems like a bug indeed.

I'm still working on revamping the toggle and toggle column components, so possibly this will be fixed soon. Still, I'll reopen this issue.

**Comment by sumardi** [comment] 2023-07-27 13:42
I can confirm this bug exists with or without calling `updateStateUsing()`.

**Comment by zepfietje** [comment] 2023-07-27 14:12
Thanks for that info, @sumardi! 😄
I'll be looking into that column real soon now.

**Comment by fgschafer** [comment] 2023-09-24 01:06
Hi, is there any follow up on this? I'm also facing the same flickering

**Comment by zepfietje** [comment] 2023-09-24 06:48
Not as far as I know.
We're working through more urgent bugs first.

Feel free to look into this issue and attempt a PR though.
Always happy to review. 😊

**Closed as completed** 2023-12-04 13:48 UTC
Labels: bug, unconfirmed, low priority
