### ISSUE TITLE
Inconsistent background color on dark mode [Chromium ONLY]

### ISSUE THREAD

**Issue by saeedvaziry** [laravel-filament/filament#14110] opened 2024-08-31 18:34 UTC
### Package

filament/filament

### Package Version

v3.2.110

### Laravel Version

11.11

### Livewire Version

v3.5.6

### PHP Version

PHP 8.2

### Problem description

The background color is inconsistent in dark mode for all chromium-based browsers including Google Chrome and Brave.

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/d40604ff-22ce-477a-9a63-5e8de791f4a4">

A workaround to solve the problem is to give the same background color to `.fi-main` 

### Expected behavior

I think it should be same color across the page

### Steps to reproduce

switch to dark mode and go to a page with less content so your browser doesn't start showing scroller.

For me, with a resolution of 2304 * 1296, it is possible to see the issue [on the demo](https://demo.filamentphp.com/blog/categories) as well 

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by andrewdwallo** [comment] 2024-09-07 11:25
Duplicate of #7759?

**Comment by saeedvaziry** [comment] 2024-09-07 17:26
@andrewdwallo yes but don't understand why closed

**Comment by andrewdwallo** [comment] 2024-09-08 12:24
I guess because it's browser specific and not an issue/bug with Filament? That is, unless it's something overlooked in Filament.

**Comment by danharrin** [comment] 2024-09-19 07:20
Issues are closed if there aren't actions we can take to fix Filament, it's like keeping an item on your todo list that is for someone else to solve. If you have any suggestions, please share or make a PR.

**Closed as completed** 2024-09-23 12:20 UTC
Labels: bug, unconfirmed, medium priority
