### ISSUE TITLE
Cannot search select field when "Tab"ing into the field and typing a single character.

### ISSUE THREAD

**Issue by JHWelch** [laravel-filament/filament#5924] opened 2023-03-13 20:49 UTC
### Package

filament/filament

### Package Version

v2.17.15

### Laravel Version

v10.3.3

### Livewire Version

v2.12.3

### PHP Version

v8.1.13

### Problem description

I am trying to make a field in a form searchable. The search general works, except when a user "Tabs" into the field and types a first character. it does not filter the results. 

I created a Reproduction repository that can be found running here. It is created to replicate the interaction in my specefic app.
https://filament-bug.jordanwelch.com/

### Expected behavior

I would expect tabbing into a searchable select and typing a single character would filter the select options by the input character. 

### Steps to reproduce

Live reproduction found here: https://filament-bug.jordanwelch.com/

1. Create a select field. 
2. Set its "Options" from a table with a closure. 
3. Mark select field searchable
4. View page, click on previous input and "Tab" into the select field
5. Type 1 character
6. View that list is not sorted. 

Here is the specific file: https://github.com/JHWelch/filament-bug/blob/main/app/Http/Livewire/ThingToTypeForm.php

### Reproduction repository

https://github.com/JHWelch/filament-bug

**Comment by danharrin** [comment] 2023-03-13 21:02
Hey, I do consider this very low priority, typing more than one character does work fine. I also expect that this is an issue with Choices.js which we use internally rather than Filament itself.

I would urge you to investigate and PR a fix yourself if this is urgent to you :)

**Comment by zepfietje** [comment] 2023-03-14 09:04
Off-topic, but I do want to compliment the clear reproduction repository you even deployed!
Makes our lives so much easier.
Thanks, @JHWelch. 🙏

**Comment by zepfietje** [comment] 2023-04-11 08:09
Closing this as there's nothing we can do since it's a bug in Choices.js.

**Closed as not planned** 2023-04-11 08:10 UTC
Labels: bug, confirmed, bug in dependency
