### ISSUE TITLE
Page scroll up using wizard and repeater on Google Chrome on Mac OS X 10.11.5 

### ISSUE THREAD

**Issue by spagnuolocarmine** [laravel-filament/filament#5852] opened 2023-03-04 10:44 UTC
### Package

filament/filament

### Package Version

v2

### Laravel Version

v8

### Livewire Version

v2

### PHP Version

8

### Problem description

Page scroll up using wizard and repeater

### Expected behavior

No scrolling to the top of the page

### Steps to reproduce

- login [test@example.com](mailto:test@example.com) - password
- edit a test resource
- scroll down and change a subitem into the last item
- the page will automatically scroll to the top

### Reproduction repository

https://github.com/spagnuolocarmine/filamentphp-bug-scrolling-select-repeater-wizard

**Comment by awcodes** [comment] 2023-04-02 13:50
This has been brought up multiple times in the discord and every time it was an issue with a browser extension and not a result of anything in Filament.

**Comment by danharrin** [comment] 2023-04-02 18:39
Which browser extensions do you have @spagnuolocarmine ?

**Comment by zepfietje** [comment] 2023-04-09 10:22
Could you provide the additional info @danharrin asked for, @spagnuolocarmine?
Otherwise it'll be hard for us to look into the issue. 🙂

**Comment by jojostx** [comment] 2023-04-11 08:14
> Could you provide the additional info @danharrin asked for, @spagnuolocarmine? Otherwise it'll be hard for us to look into the issue. 🙂

I had a similar issue on windows 10, (freshly installed) Firefox and chrome browsers. After some digging, I *may* have found the cause. In the file, `Filament/forms/resources/views/components/wizard.blade.php` in the alpinejs function `scrollToTop` on line 45, the call to `this.$el` is properly assigned to the wizard component when the page loads but after you navigate to the next step of the wizard component, it get reassigned to the next button. This behavior only happens when `this.$el` is accessed but not when `$el` is accessed. 
![Screenshot (57)](https://user-images.githubusercontent.com/42269899/231098408-1765373c-4079-41a8-8dfb-6891d069fcda.png)

**Comment by zepfietje** [comment] 2023-04-11 08:24
Thanks for looking into this issue, @jojostx.
I'm not sure if I'm following though.
`$el` always references the wizard component, not any of the buttons.
Could you clarify?

Edit: or maybe I'm wrong actually. 🤔
What if we use `this.$root` instead of `this.$el`?
We want the wizard to scroll into view, not the buttons, right?

**Comment by danharrin** [comment] 2023-04-11 10:26
Yeah the `$root` should be used here. I thought that if a method was defined on the root, $el === $root regardless of the method that called it

**Comment by zepfietje** [comment] 2023-04-11 10:27
That was my thinking too to be honest...

**Comment by danharrin** [comment] 2023-04-30 15:43
Can't reproduce this myself but I've submitted the potential fix - #6361

**Closed as completed** 2023-04-30 15:43 UTC
Labels: bug, needs more info, unconfirmed

**Comment by zepfietje** [comment] 2023-05-01 07:03
After thinking about this once more, I don't think `$root` vs `$el` should make any difference actually... @danharrin

But if we can't reproduce and the potential fix doesn't break anything, this is fine to me. 👍
