### ISSUE TITLE
Select box not disabling correctly when using closure and multiple

### ISSUE THREAD

**Issue by davidabadi** [laravel-filament/filament#8935] opened 2023-10-06 22:34 UTC
### Package

filament/forms

### Package Version

v3.0.69

### Laravel Version

v10.26.2

### Livewire Version

v3.0.5

### PHP Version

PHP 8.2.5

### Problem description

When using a Select input with the ability to select multiple on a form and having it disabled dinamically depending on another input (a toogle in this case) the input changes color as if it is disabled but it still allows the user to select a value. If I use the disabled property outright (->disabled()) on the select it does work as expected and it does not allow the user to select a value. 
<img width="657" alt="image" src="https://github.com/filamentphp/filament/assets/33469462/d0820e52-f58c-4ff7-9b4c-4853de247918">

### Expected behavior

Select box should become disabled and user is not allowed to select any value.

### Steps to reproduce

Create a form with the following fields 

`Select::make('users')->options(User::orderBy('name')->pluck('name', 'id'))->multiple()->disabled(fn(Get $get) => $get('select_all')),
Toggle::make('select_all')->live(onBlur: true)`

### Reproduction repository

https://github.com/davidabadi/filamentFormBug

**Comment by zepfietje** [comment] 2023-10-07 07:04
Please search existing issues before creating a bug report.
This is a duplicate of https://github.com/filamentphp/filament/issues/3068 and a couple of other dupes that have been reported since.

**Closed as not planned by zepfietje** 2023-10-07 07:04 UTC
Labels: bug, unconfirmed, low priority
