### ISSUE TITLE
Custom Guard for each panel return Session Database user_id to null

### ISSUE THREAD

**Issue by MarJose123** [laravel-filament/filament#9581] opened 2023-11-11 03:24 UTC
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### PHP Version

8.2

### Problem description

When logging in to a default panel with a declared `authGuard('web')` is working fine however, logging in to other panel with a custom authguard it failed to add user id in the session table.

### Expected behavior

custom guard supposed to be working.

### Steps to reproduce

1. Create a two different panel
2. Create a custom Authenticatable model
3. Create a custom guard and provider using the `eloquent` provides
4. Add the guard to the panel
5. login to the panel that use the custom guard
6. check the session table in the database, then `user_id` column is `null`

### Reproduction repository

https://github.com/OSSAdmiral/Recruit/

**Comment by MarJose123** [comment] 2023-11-11 03:28
For additional information, please see below information that might help resolve the issue more faster.

`auth.php`
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
        'candidate_web' => [
            'driver' => 'session',
            'provider' => 'candidates',
        ],
    ],
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
        'candidates' => [
            'driver' => 'eloquent',
            'model' => App\Models\CandidateUser::class,
        ],
```

here are the panel configurations.

for the panel that used the custom guard:
```
return $panel
            ->id('candidate')
            ->path('portal/candidate')
            ->authGuard('candidate_web')
            ->authPasswordBroker('candidate_users')
            ->passwordReset()
            ->emailVerification()
            ->login()
  //...
```
for the panel that used the default guard:
```
return $panel
            ->default()
            ->maxContentWidth('full')
            ->id('recruit')
            ->path('')
            ->passwordReset()
            ->authGuard('web')
            ->authPasswordBroker('users')
            ->emailVerification()
            ->login()
 //....
```

**Comment by MarJose123** [comment] 2023-11-11 03:29
I have an assumption that the filament uses the default `web` guard and doesn't respect the provided guard under the panel configuration  `->authGuard('candidate_web')`

**Comment by danharrin** [comment] 2023-12-08 15:51
Hi, please create a new repository. We would like a minimal reproduction of the issue, with thorough instructions, instead of having to install your entire app with all its dependencies and feature.

Also, creating a new repository can sometimes help you figure out that the issue is on your side and not with Filament.

**Comment by MarJose123** [comment] 2023-12-09 07:50
> Hi, please create a new repository. We would like a minimal reproduction of the issue, with thorough instructions, instead of having to install your entire app with all its dependencies and feature.
> 
> Also, creating a new repository can sometimes help you figure out that the issue is on your side and not with Filament.

Hi Thank you for your response.

I've create a fresh installation with Filament, and setup the a two different panels, however during the time I access the web page for the 2nd panel (`the panel path setup is `->path('');`) it return an error `Route [login] not defined.` it supposed to be a login page of the 2nd panel.

I can't move forward and reproduce the issue I've encountered for the session database since I've encountered a new issue. not sure if it is only me.

Installed Filament version: `v3.1.17`

Here is the Repository https://github.com/MarJose123/example1

![image](https://github.com/filamentphp/filament/assets/18107626/12d1bd17-fde4-4397-b3ee-378056bc9539)

**Comment by danharrin** [comment] 2023-12-09 08:13
Laravel requires it. You just need to define a route with the name "login" that redirects to the main login page. I usually put it at the /laravel/login

**Comment by MarJose123** [comment] 2023-12-09 09:27
I know that `Route [Login] not defined` error is from the `Authenticate` middleware but it will only occur if you visit a page that required authentication and laravel will force you to authenticate by sending the route to login page.

In my case I'm navigating only to the `http://127.0.0.1:8000/` as defined in my panel path `->path('/')` as mentioned in the [documentation](https://filamentphp.com/docs/3.x/panels/configuration#changing-the-path) to login to the filament.

**Comment by danharrin** [comment] 2023-12-09 23:17
You need `->login()` for the `StandardPanelProvider` otherwise we cant redirect the user anywhere.

**Comment by danharrin** [comment] 2024-01-08 13:40
Closing this as I think `->login()` solves, let me know otherwise

**Closed as not planned by danharrin** 2024-01-08 13:40 UTC
Labels: bug, needs more info, unconfirmed, low priority
