### ISSUE TITLE
Select options: change options array -> state no selected (native only)

### ISSUE THREAD

**Issue by MichaelMdp** [laravel-filament/filament#8972] opened 2023-10-09 11:44 UTC
### Package

filament/filament

### Package Version

v3.0.62

### Laravel Version

10.24.0

### Livewire Version

v3.0.5

### PHP Version

8.1.16

### Problem description

On a filament forms select field:
After you have a value selected for the an option, if you change the items created by the options closure
(e.g.: remove an item from the list)
The selected value is no longer selected in the UI, even if it has the exact same key.

When the property is flagged as a url param, you can refresh the page and the value is selected again.

It only seems to occur when an item, before the selected item, is removed from the options array.
When the first item was selected and items after the selection are removed, it stays selected.

This was working in v2.
this issue is only present for the native select.

### Expected behavior

the selected value stays selected in the UI, even if the underlying options array is updated. 

### Steps to reproduce

artisan migrate:fresh
go to the homepage /
a form is visible with 2 dropdowns.

<img width="724" alt="image" src="https://github.com/filamentphp/filament/assets/1629670/9c1d62ed-aee0-4e30-9dac-ef564eb2bf33">

- select one of the 2 last values of the first select (form Value1): 1 or 2
- select any value of the second select (form Value2)
- once the second dropdown is selected, the options of select 1 get updated and the first 3 values are removed.

=> the initial selection is no longer visualised in the UI.
<img width="743" alt="image" src="https://github.com/filamentphp/filament/assets/1629670/9146ff4c-9279-4780-9677-161725c97905">

see App\Livewire\DropdownTest.php

### Reproduction repository

https://github.com/MichaelMdp/filamentv3-options-update-issue

**Comment by zepfietje** [comment] 2023-10-09 12:52
Might this be caused by this Livewire bug, @MichaelMdp?
https://github.com/livewire/livewire/pull/6984

**Comment by austincarpenter** [comment] 2023-10-16 00:32
Could be this too https://github.com/livewire/livewire/pull/6889

**Comment by zepfietje** [comment] 2023-10-16 09:27
Oh, I think I was actually looking to reference your PRs, @austincarpenter. 😄

Closing as this is most probably https://github.com/filamentphp/filament/pull/8633.

**Closed as not planned by zepfietje** 2023-10-16 09:27 UTC
Labels: bug, unconfirmed, low priority
