### ISSUE TITLE
Disabled searchable select field not enabled after updating

### ISSUE THREAD

**Issue by mohamedmoussasoli** [laravel-filament/filament#5162] opened 2022-12-04 10:47 UTC
### Package

filament/filament

### Package Version

v2.16.53

### Laravel Version

v9.42.2

### Livewire Version

v2.10.7

### PHP Version

^8.0

### Problem description

I have a reactive checkbox when click on it the state of searchable select field disabled attribute is not updated well

### Expected behavior

The searchable select field should be enabled.

### Steps to reproduce

1 - go to create product at the top you will see checkbox with to select fields below one is searchable and the second is not both are disabled 
2 - click on enable checkbox
3 - both fields should be enabled but the searchable one is not enabled! 

### Reproduction repository

https://github.com/mohamedmoussasoli/filament-bug

**Comment by zepfietje** [comment] 2022-12-04 10:54
Hey @mohamedmoussasoli! Please search existing issues before opening a bug report. This issue is a limitation of Choices.js and has been reported many times before. It's a duplicate of:

- https://github.com/filamentphp/filament/issues/3068
- https://github.com/filamentphp/filament/issues/3566
- https://github.com/filamentphp/filament/issues/3785
- https://github.com/filamentphp/filament/issues/4329

**Closed as not planned** 2022-12-04 10:54 UTC
Labels: bug, unconfirmed
