### ISSUE TITLE
Showing the name of pressed key on keyboard on SELECT object

### ISSUE THREAD

**Issue by fatehiman** [laravel-filament/filament#13819] opened 2024-08-05 14:47 UTC
### Package

filament/filament

### Package Version

3.2.0

### Laravel Version

11.0

### PHP Version

8.3.0

### Problem description

in forms, when using keboard TAB to focus on SELECT element that is searchable(), then press Arrow key down or up or press F4 to open the select listbox, the first item in the list will be a text that contains pressed key name on keyboard! for example Arrowup, Arrowdown, F4, etc.

### Expected behavior

this text should not be shown

### Steps to reproduce

no sample source code needed, just create a SELECT element in a Form (in a resource file) that is searchable().
then focus on it by pressing TAB by keyboard, after focus, press keyboard arrow keys or F4 and see the first element of the selectbox that is a text contains "arrowup", "arrowdown" or "F4" string!

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/fatehiman/filament-issues

**Comment by fatehiman** [comment] 2024-08-05 14:51
![Screenshot 2024-08-05 181949](https://github.com/user-attachments/assets/0ced136c-32fb-4362-89f1-1236ccc372e5)

**Comment by zepfietje** [comment] 2024-08-06 07:33
Duplicate of https://github.com/filamentphp/filament/issues/5707.

**Comment by zepfietje** [comment] 2024-08-06 07:34
This does seem to be fixed in the next major version of Choices.js: https://github.com/Choices-js/Choices/pull/1104.

**Closed as not planned by zepfietje** 2024-08-06 07:33 UTC
Labels: bug, unconfirmed, medium priority
