### ISSUE TITLE
Select multiple options UX is inconsistent

### ISSUE THREAD

**Issue by scottgrayson** [laravel-filament/filament#6822] opened 2023-06-20 18:54 UTC
### Package

filament/filament

### Package Version

v2.17.41

### Laravel Version

v10.11.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.6

### Problem description

Select multiple hides an option once it is selected. This is expected.

But, when editing and selected options are loaded from a relationship, those options are still shown in the dropdown.

### Expected behavior

Selections loaded on hydration should act the same way as selections made during edit

### Steps to reproduce

1. Edit a product
2. click category select
3. see selected categories are shown in option dropdown (bug)
4. select a category option
5. see the selection is removed from the options list (expected)

### Reproduction repository

https://github.com/TappNetwork/filament-demo/tree/multiselect-bug

**Comment by danharrin** [comment] 2023-06-20 20:47
Duplicate of #2363.

**Closed as not planned by danharrin** 2023-06-20 20:47 UTC
Labels: bug, unconfirmed
