### ISSUE TITLE
Tooltips on actions don't dispose correctly on polled table

### ISSUE THREAD

**Issue by robinmiau** [laravel-filament/filament#14265] opened 2024-09-16 16:23 UTC
### Package

filament/filament

### Package Version

v3.2.112

### Laravel Version

v11.23.5

### Livewire Version

v3.5.6

### PHP Version

PHP 8.3.11

### Problem description

I have actions with tooltips for my polling table, and when the table updates the tooltip remains visible.

![Bildschirmaufnahme2024-09-16175744-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/c7c99042-a905-479b-a521-0fd112c26aba)

*(Couldn't show everything from the table, but there were always new entries)*

It only disappears when you scroll.

### Expected behavior

The tooltips should not be visible when the cursor is no longer over the action.

### Steps to reproduce

1. Add `->poll()` to the table.
2. Add `->tooltip()` to an action.
3. Hover over an action to see its tooltip.
4. When the table refreshes and there is a new entry, the tooltip remains visible even if you move the cursor away from it.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment] 2024-09-26 10:48
Duplicate of https://github.com/filamentphp/filament/issues/11599.

**Closed as not planned by zepfietje** 2024-09-26 10:48 UTC
Labels: bug, unconfirmed, medium priority
