### ISSUE TITLE
SpatieMediaLibraryFileUpload does not work with Builder / Block

### ISSUE THREAD

**Issue by dinandmentink** [laravel-filament/filament#5911] opened 2023-03-12 12:56 UTC
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v2.17.14

### Laravel Version

v10.x (irrelevant)

### Livewire Version

v2.12.3 (irrelevant

### PHP Version

v8.1 (irrelevant)

### Problem description

When uploading files using `SpatieMediaLibraryFileUpload` they are stored with the related model, but not the specific Block. This means that any uploaded file will be displayed with ALL blocks. 

I have considered the following workaround: It's possible to specify a different collection for different Blocks. However, uploaded files to different Blocks using the same Block type they will still be added to all Blocks of the same type.

### Expected behavior

I would expect `SpatieMediaLibraryFileUpload` to upload files to a specific Block instance. For example when adding an Image Block and then another Image Block I expect to be able to upload two different images.

### Steps to reproduce

Given a `Page` model and a `PageResource`. 

When I add a builder like this:

```php
Forms\Components\Builder::make('blocks')->blocks([
    Forms\Components\Builder\Block::make('image')->schema([
        Forms\Components\SpatieMediaLibraryFileUpload::make('visual'),
    ]),
]),
```
And then procede to add an image to a Block, this same image will be added to _all_ Blocks of the image type. 

Before saving:

![image](https://user-images.githubusercontent.com/17289887/224541539-43e094c5-668a-4264-bf6c-193f8061f70d.png)

Aftter saving:

![image](https://user-images.githubusercontent.com/17289887/224541577-584e8a6a-0f0b-4677-923a-c2bcd3f46429.png)

Note how both images are added to the `Page` model, but without any way to distinguish the block they belong to:

![image](https://user-images.githubusercontent.com/17289887/224541697-d3b9f8eb-6f86-4780-b1b0-4fe4cfe45370.png)

![image](https://user-images.githubusercontent.com/17289887/224541705-b7a3fd1d-ca56-4f52-af94-6bb48de2984e.png)

More detailed steps described in: https://github.com/dinandmentink/filament-spatie-bug-example

Some considerations:

- I'm not sure how to fix this but maybe the `Spatie\MediaLibrary\MediaCollections\Models\Media` `id` could be stored as the value. Currently nothing is stored for the file in the blocks json.
- For display it would also help a lot if the `Media` `id` would be stored. This could be used to retrieve the Media and then render it.

### Reproduction repository

https://github.com/dinandmentink/filament-spatie-bug-example

**Comment by danharrin** [comment] 2023-03-12 13:06
Duplicate of #1284, media library isn't built for this unfortunately, storing the media ID in the JSON is not safe since it could be deleted in another place, and since there is no referential integrity, the file upload would break. I would advise using a normal file upload for this. If you have other suggestions, feel free to PR them.

**Closed as completed by danharrin** 2023-03-12 13:06 UTC
Labels: bug, unconfirmed

**Comment by dinandmentink** [comment] 2023-03-15 21:26
Thanks for the response. That's a shame as I would really like to use medialibrary with the Builder / Repeater.  The default image/file upload does not allow for multiple conversions and responsive images.

The https://github.com/whitecube/nova-flexible-content does allow for this in laravel nova by adding the block's id to the medialibrary collection. 

I'll see if I can get that behaviour to work. Thanks for the reply.

**Comment by danharrin** [comment] 2023-03-15 21:33
Media library uses https://github.com/spatie/image-optimizer for optimisations so maybe just use that
