### ISSUE TITLE
Searchable select runs unnecessary queries

### ISSUE THREAD

**Issue by anatolyeltsov** [laravel-filament/filament#4535] opened 2022-10-13 22:00 UTC
### Package

filament/filament

### Package Version

v2.16.32

### Laravel Version

v9.35.1

### PHP Version

PHP 8.1.8

### Problem description

Unnecessary queries.
Or maybe I've misunderstood docs and doing something completely wrong?

### Expected behavior

No unnecessary queries.

### Steps to reproduce

Noticed it in my project and reproduced on clean install:

1. Install latest versions of Laravel, Filament and Laravel Debugbar
2. Create Test and Subtest models and resources with belongsTo relationship
3. Add Select for test_id field on Subtest create/edit page (tried different variants, all have issues)

3.1 Runs query on page load and then again same query when the field is clicked:
```
Forms\Components\Select::make('test_id')
  ->relationship('test', 'id')
  ->preload()
  ->searchable(),
```
![Screenshot from 2022-10-14 00-44-14](https://user-images.githubusercontent.com/54027342/195716844-37d30c89-326b-4230-bace-36ff109c8ffd.png)
3.2 Same result as in 3.1 when callback is used in relationship():
```
Forms\Components\Select::make('test_id')
  ->relationship('test', 'id', function($query) {
    return $query;
  })
  ->preload()
  ->searchable(),
```
3.3 Same result as in 3.1 when options with callback is used:
``` 
Forms\Components\Select::make('test_id')
  ->options(function() {
    return Test::all()->pluck('id', 'id');
  })
  ->searchable()
```
3.4 Works as expected on create/edit page, but runs additional queries row on list page (I have 5 rows of Subtest and it runs 7 duplicated queries for whatever reason):
```
Forms\Components\Select::make('test_id')
  ->options(Test::all()->pluck('id', 'id'))
  ->searchable(),
```
![Screenshot from 2022-10-14 00-50-32](https://user-images.githubusercontent.com/54027342/195717790-bc1b80ef-b583-42cd-a4d1-a77b2d1ab8bb.png)

I've added all four variants to SubtestResource in provided repository.

### Reproduction repository

https://github.com/anatolyeltsov/filament-queries

**Comment by zepfietje** [comment] 2022-10-14 07:26
Hey @anatolyeltsov!

Case 3.4 can be solved by wrapping the options in a closure:

```php
Forms\Components\Select::make('test_id')
    ->options(fn () => Test::all()->pluck('id', 'id'))
    ->searchable(),
```

The duplicate queries occur due to the options argument being called multiple times internally. Wrapping it in a closure makes sure it's only evaluated once.

**Comment by anatolyeltsov** [comment] 2022-10-14 09:43
@zepfietje yeah, but then it's like 3.3 - with issue on create/edit page

**Comment by danharrin** [comment] 2022-11-12 20:41
I can only reproduce 3.4 - the rest only use 1 query in the latest version of Filament. We probably fixed it at some point.

**Comment by zepfietje** [comment] 2022-11-12 20:46
@danharrin, 3.4 will be fixed in Filament v3, right? That means we can close this issue?

**Comment by danharrin** [comment] 2022-11-12 20:49
Yeah 3.4 is a flaw in how v2 is built. v2 relies on calculating the form schema for each action on the list page every time it loads, since it needs to work out if a modal can be opened or not from each button. In v3 we do this only when the button is clicked.

**Closed as completed by danharrin** 2022-11-12 20:49 UTC
Labels: bug, unconfirmed
