### ISSUE TITLE
Using `->searchable()` and `->disabled()` with the form builder results in the item not being displayed.

### ISSUE THREAD

**Issue by bzy107** [laravel-filament/filament#9314] opened 2023-10-26 16:20 UTC
### Package

filament/filament

### Package Version

v3.0.83

### Laravel Version

v10.29.0

### Livewire Version

v3.0.10

### PHP Version

PHP 8.2.11

### Problem description

I want to enable the second select box when the first select box is filled out in a scenario where there are two select boxes. 
However, when I use `->searchable()` on the second select box, the second select box doesn't appear after selecting the first one.

![スクリーンショット 2023-10-27 1 18 37](https://github.com/filamentphp/filament/assets/28666304/adcdf154-d2e3-4101-9672-dbe080e5e098)

Please keep in mind that I'm a beginner with Livewire and Filament. Thank you.

### Expected behavior

The second select box should appear after selecting the first select box.

### Steps to reproduce

```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('type')
                    ->options([
                        'cat' => 'Cat',
                        'dog' => 'Dog',
                        'rabbit' => 'Rabbit',
                    ])
                    ->live()
                    ->searchable()
                    ->required(),
                Forms\Components\Select::make('type2')
                    ->options([
                        'cat2' => 'Cat2',
                        'dog2' => 'Dog2',
                        'rabbit2' => 'Rabbit2',
                    ])
                    ->searchable()
                    ->disabled(function (Get $get) {
                        return $get('type') === null;
                    }),
            ]);
    }
```

### Reproduction repository

https://github.com/bzy107/filament-select-bug/tree/main

**Comment by andrewdwallo** [comment] 2023-10-26 18:14
This has been an issue before. It is a result of a limitation with Choices.js. Duplicate of #3068 and many others.

**Comment by bzy107** [comment] 2023-10-26 18:46
I'm sorry. It's a known issue. I'll close it.

**Closed as completed** 2023-10-26 18:46 UTC
Labels: bug, unconfirmed, low priority
