### ISSUE TITLE
requiresConfirmation doesn't work on suffixActions in Infolists

### ISSUE THREAD

**Issue by saeedvaziry** [laravel-filament/filament#14319] opened 2024-09-22 11:09 UTC
### Package

filament/filament

### Package Version

v3.2.113

### Laravel Version

11.23.5

### Livewire Version

v3.5.8

### PHP Version

8.2.18

### Problem description

requiresConfirmation doesn't open the confirmation modal when being used on an action inside an infolist text entry

https://github.com/user-attachments/assets/97d64ee0-96fd-4461-9430-af35758a9369

### Expected behavior

it should open the confirmation modal

### Steps to reproduce

Clone this repo and try it 

https://github.com/saeedvaziry/filament-requires-confirmation-issue/blob/81eecb360beddf2a27f4bb0b09e4ee918b395576/app/Filament/Resources/UserResource/Pages/ViewUser.php#L42

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/saeedvaziry/filament-requires-confirmation-issue

**Comment by saeedvaziry** [comment] 2024-09-27 16:31
@zepfietje any clue where the issue relies? would like to work on a PR.

**Comment by zepfietje** [comment] 2024-09-30 13:19
I haven't been able to check out your reproduction repo yet.
Does a similar action work when placed elsewhere on the page?

**Comment by saeedvaziry** [comment] 2024-09-30 14:23
So far I've seen weird behaviour when using suffixActions.

For example: the modal works fine if the suffixAction is in a form field inside a Table action like the video below:

https://share.cleanshot.com/K8nNkV3K

Also works when the suffixAction is in a form inside a Header Action but a bit weird behaviour (closing the original modal):

https://share.cleanshot.com/67TCC265

But when I use it inside a page (Resource page or normal filament page) it responds with `open-modal` but no modal opens.

**Comment by felabrecque** [comment] 2024-10-03 14:26
I have a similar problem, but with hintAction inside and infolist.
The problem doesn't seem to be with the click detection on the action button.
It even dispatch an 'open-modal' event.
But the modal doesn't seem to be added to the html, so alpineJs x-on "open-modal" is not included in the webpage.

**Comment by felabrecque** [comment] 2024-10-03 14:39
The problem is that the modals html is not loaded.

I added this line in vendor/filament/infolists/resources/views/component-container.blade.php just before the closing DL
<x-filament-actions::modals />

And it worked

You can copy the file into your folder: resources/views/vendor/filament-infolists
and edit it there.

Tested prefixAction, suffixAction & hintAction

**Comment by saeedvaziry** [comment] 2024-10-03 15:11
@felabrecque great finding! worked for me

**Comment by danharrin** [comment] 2024-12-11 10:59
If you are not using the Filament `<x-filament::page>` component as described in the docs, which contains the modals, you need to pull those in yourself. It is the same if you were creating a custom Livewire component. It should be added to the main page view, not the `component-container.blade.php`.

**Closed as not planned by danharrin** 2024-12-11 10:59 UTC
Labels: bug, unconfirmed, medium priority
