### ISSUE TITLE
Simple resource - delete button error

### ISSUE THREAD

**Issue by leandrocfe** [laravel-filament/filament#7190] opened 2023-07-24 18:53 UTC
### Package

filament/filament

### Package Version

v3.0.0-beta9

### Laravel Version

v10.15.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.8

### Problem description

JavaScript Error Occurs When Clicking on Modal Edition and Subsequently on the Delete Button

https://github.com/filamentphp/filament/assets/3833889/25b4f1ec-ecbd-416b-9d25-42e73bf81c2b

### Expected behavior

The delete modal behavior

### Steps to reproduce

Click on edit action and after the delete button

### Reproduction repository

https://github.com/leandrocfe/filament-v3-issues.git

### Relevant log output

```shell
VM12316:1 Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at livewire.js?id=3605227a:1816:25
    at Array.reactiveEffect (livewire.js?id=3605227a:2050:18)
    at flushJobs (livewire.js?id=3605227a:465:15)
```

**Comment by zepfietje** [comment] 2023-07-24 19:44
Duplicate of https://github.com/filamentphp/filament/issues/7064.

**Closed as not planned by zepfietje** 2023-07-24 19:44 UTC
Labels: bug, unconfirmed

**Comment by mustofa1945** [comment] 2024-12-13 17:08
Bro!! My delete button is not working properly in bulks action, how to fix that?
