### ISSUE TITLE
Unexpected behavior when removing a repeater item that contains an input select

### ISSUE THREAD

**Issue by joaovdiasb** [laravel-filament/filament#7563] opened 2023-08-08 15:44 UTC
### Package

filament/filament

### Package Version

3.0.12

### Laravel Version

10.17.1

### PHP Version

8.2

### Problem description

When I try to remove an item from the repeater, it doesn't respond as expected

### Expected behavior

The repeater item will be removed

### Steps to reproduce

Its possible reproduce on [demo.filament](https://demo.filamentphp.com/) - Orders > Create (wizard step 2)

https://github.com/filamentphp/filament/assets/51106311/88277a5b-3138-42c2-8815-252d337afcdd

### Reproduction repository

https://github.com/joaovdiasb/demo

### Relevant log output

<img width="702" alt="CleanShot 2023-08-08 at 12 40 47@2x" src="https://github.com/filamentphp/filament/assets/51106311/9063c8b2-ec0f-4fe9-a767-01c355d9d0d0">

**Comment by danharrin** [comment] 2023-08-09 06:58
Duplicate of #7485

**Closed as not planned by danharrin** 2023-08-09 06:58 UTC
Labels: bug, unconfirmed

**Comment by mustafa-online** [comment] 2023-08-09 08:21
Confirmed here too

**Comment by danharrin** [comment] 2023-08-09 15:38
livewire/livewire#6289
