### ISSUE TITLE
RichEditor doesn't defer data binding

### ISSUE THREAD

**Issue by gbrock** [laravel-filament/filament#8563] opened 2023-09-18 06:46 UTC
### Package

filament/filament

### Package Version

v3.0.52

### Laravel Version

v10.23.1

### Livewire Version

v3.0.5

### PHP Version

PHP 8.1.6

### Problem description

The RichEditor triggers Livewire updates on every keypress by default (without `->live()`), rather than doing deferred updates.  This behavior is also present when `onBlur: true` is set.

### Expected behavior

The RichEditor to be live only when configured so, and binding to be deferred (not throwing a ton of network requests) by default.

### Steps to reproduce

1. Add a RichEditor to a form, and don't add `->live()`.
2. Test it in the browser.  While typing in the RichEditor, inspect the network to see all those requests.

### Reproduction repository

https://github.com/gbrock/filament-unliving-rich-editor-issue

**Comment by vanhooff** [comment] 2023-09-18 13:43
Could we revisit the priority label on this? The RichEditor is completely broken right now, because as soon as you start typing it loses focus.

**Comment by zepfietje** [comment] 2023-09-25 13:02
This was caused by a Livewire bug and has been fixed last week.
Also a fix has been implemented in Filament to ensure this issue doesn't occur on older Livewire versions.

Please comment on here if you're still experiencing this bug.

**Closed as completed by zepfietje** 2023-09-25 13:02 UTC
Labels: bug, unconfirmed, high priority
