### ISSUE TITLE
Select options look weird in Chrome on Windows

### ISSUE THREAD

**Issue by anthonyphysgun** [laravel-filament/filament#7127] opened 2023-07-21 22:00 UTC
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

10.10

### PHP Version

8.1

### Problem description

Dropdowns don't have styling and appear fully white when on dark mode

### Expected behavior

Them to be dark mode

### Steps to reproduce

Make a dropdown on anything and it wont be styled 

### Reproduction repository

https://github.com/anthonyphysgun/filament-toggleissue

**Comment by anthonyphysgun** [comment] 2023-07-21 22:07
env is windows on chrome - seems to be fine on macos

**Comment by zepfietje** [comment] 2023-07-23 09:56
@anthonyphysgun, could you share some screenshots of this?
I have no idea what could be the cause of this.
Also, since we're not on Windows, it's impossible for us to reproduce.

**Comment by anthonyphysgun** [comment] 2023-07-23 14:38
https://discord.com/channels/883083792112300104/883083792653381695/1132064814949204008

**Comment by zepfietje** [comment] 2023-07-23 17:09
Oh you're talking about the select input.
I thought you meant the dropdown component.

Pasting the image from your Discord message here as reference:

![image](https://github.com/filamentphp/filament/assets/44533235/b03542cb-e2ff-43f3-b0c9-9351c623d1fd)

Most probably it's out of our control, as the options shown when focusing the select are just styled by the OS/browser.

Could you provide these additional details?

1. Screenshot as above, but when using the Filament light theme.
2. Screenshot of the options in a regular Filament select form component in light and dark theme.
3. Screenshot of the unstyled HTML `select` in dark and light (e.g. from this page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).

As I can't reproduce the issue on macOS (Safari/Firefox/Chromium), I'm going to close this issue until further evidence (as outline in the list above) proves this actually is a Filament issue (which I'm pretty sure it's not, but never say never).

Let us know! 🙂

**Comment by anthonyphysgun** [comment] 2023-07-24 16:04
![image](https://github.com/filamentphp/filament/assets/129686033/45027191-73b8-4bdf-aaaf-638016cf8b71)
![image](https://github.com/filamentphp/filament/assets/129686033/4df8cec5-f57c-429a-90ef-811e3f96ed8b)

v2 vs v3

![image](https://github.com/filamentphp/filament/assets/129686033/e9313a58-215b-49db-b089-e6f1b5c8f454)
Light Theme v3

![image](https://github.com/filamentphp/filament/assets/129686033/78c583be-f8ec-43ae-bb5c-732350f2e9bc)

**Comment by zepfietje** [comment] 2023-07-24 17:01
Okay so the inset is because the select is now wrapped in an affixes component that's also used for the forms select field to ensure consistency. So not a lot we can do there I think.

The remaining major issue would be that the select options background is white in dark mode?

**Comment by zepfietje** [comment] 2023-07-24 17:03
It's hard for me to debug as I'm not on Windows, but maybe you could try setting an actual background color on the `select` element?

Just a wild guess, but it might be that in v2 that `select` had a dark background color, whereas it's transparent in v3 since the affixes component handles the background.

**Comment by qcol** [comment] 2023-07-25 13:40
![image](https://github.com/filamentphp/filament/assets/358993/b5907e9a-c4a8-4ce8-a607-1a2840d84bff)

In my case chrome / ubuntu
In the expanded Select field in Dark Mode, only the highlighted text is visible, the rest is white on a white background. Fresh installation.
The first display of the expanded Select shows the text, but when the item is selected next time text disappears

**Comment by zepfietje** [comment] 2023-07-25 15:01
Could you try what I suggested in the comment above, @qcol?

> maybe you could try setting an actual background color on the select element?

If you could share a screenshot of that, I can implement a fix.

**Comment by qcol** [comment] 2023-07-25 16:22
![image](https://github.com/filamentphp/filament/assets/358993/5bf6e8f2-33b4-45ed-b36f-391647c0e1ab)

If you mean the console test, it looks like this in the screenshot. The text is now readable, but the corners look bad, the bottom border of the dropdown list is missing.

**Comment by zepfietje** [comment] 2023-07-25 16:41
Thanks!

The corners issue is caused by the `select` element overflowing the `affixes` component.
That's required for the searchable select, but I can possibly add the rounding to the `select` itself for a default HTML select.
I'd have to account for any affixes though, but I think I can make that work.

The remaining issue would then be the border.
Could you look into the cause of that?

**Comment by qcol** [comment] 2023-07-25 17:40
There is no bottom border in the light theme either. As far as I can see the reason is the shadow effect? 

![image](https://github.com/filamentphp/filament/assets/358993/22dc4783-aa88-45a5-8c13-8fec525a484d)

**Comment by zepfietje** [comment] 2023-07-25 18:15
That shadow isn't applied by Filament though.

**Comment by zepfietje** [comment] 2023-07-25 18:15
Could you check if just a plain HTML `select` in a simple HTML file outside Filament looks the same?

**Comment by qcol** [comment] 2023-07-25 19:38
sure:

![image](https://github.com/filamentphp/filament/assets/358993/480aeb00-6427-46ba-a60a-7b168469066f)

**Comment by qcol** [comment] 2023-07-25 20:11
Select with ->multiple() option looks correct:

![image](https://github.com/filamentphp/filament/assets/358993/b2800f30-a128-4e8d-9446-9a4261011753)

**Comment by leandrocfe** [comment] 2023-07-25 20:14
Hey, here:
chrome / Filament v3.0.0-beta10
![image](https://github.com/filamentphp/filament/assets/3833889/561cb5c6-d6ac-440a-8809-a53c662338e9)

**Comment by qcol** [comment] 2023-07-25 20:28
> Hey, here: chrome / Filament v3.0.0-beta10 

Interesting. Windows? Mac? Linux?

**Comment by qcol** [comment] 2023-07-25 20:34
options do not scale when zoomed in with ctrl+ (->multiple() scales correctly)

![image](https://github.com/filamentphp/filament/assets/358993/2d701a57-8420-4522-84cb-bbe31dc3181b)

**Comment by leandrocfe** [comment] 2023-07-25 20:38
Ubuntu
With zoom
![image](https://github.com/filamentphp/filament/assets/3833889/5a034ba5-c5e4-4665-ab55-bc710b524dd3)

**Comment by qcol** [comment] 2023-07-25 20:43
My mistake, on a fresh installation zooming  is OK.

**Comment by danharrin** [comment] 2023-07-25 20:50
Unsubscribing from this thread as the notifications are excessive, @zepfietje DM me if you need anything regarding this

**Comment by zepfietje** [comment] 2023-07-26 06:27
> Select with ->multiple() option looks correct:
> 
> ![image](https://user-images.githubusercontent.com/358993/256024968-b2800f30-a128-4e8d-9446-9a4261011753.png)

That's not using the HTML `select` so totally unrelated.

**Comment by zepfietje** [comment] 2023-07-26 06:31
As this issue is very specific to OS and browser, it's impossible for me to fix on my machine.

I'm open to pull requests that improve the native `select` design though.
Closing this issue since there isn't anything I can do really.

**Closed as not planned by zepfietje** 2023-07-26 06:31 UTC
Labels: bug, confirmed, needs more info

**Comment by qcol** [comment] 2023-07-27 09:36
Strange because on the same system and the same browser in v2 it is OK. I understand it's not a priority issue now but worth revisiting in the future. 

![image](https://github.com/filamentphp/filament/assets/358993/576de702-e8a9-43f5-b9d2-d1785315401c)

**Comment by zepfietje** [comment] 2023-07-27 09:57
I'm not denying it's a bug, and I know in v2 it probably worked because of the background color on the `select` element.

However, since this seems to work differently across OSes and browsers, there isn't a reliable way for me to test a fix. That's why I suggest individuals creating PRs that fix their case.

So, if you're able to find a fix, create a pull request and I'll review it. 🙂

**Comment by mtsunu** [comment] 2023-08-01 15:50
you can add this css to fix the colors

```css
.fi-select-input:is(.dark .dark\:text-white) > option {
    --tw-bg-opacity: 1;
    --tw-ring-color: hsla(0,0%,100%,.1);
    --tw-text-opacity: 1;
    background-color: rgba(var(--gray-900),var(--tw-bg-opacity));
    color: rgb(255 255 255/var(--tw-text-opacity));
}
```

**Comment by zepfietje** [comment] 2023-08-01 18:59
Could you reduce this to a simple `@apply` statement with Tailwind CSS classes?

**Comment by mtsunu** [comment] 2023-08-02 02:17
Like this?

```css
.fi-select-input > option {
   @apply dark:bg-gray-900;
}
```

can't test it.

**Comment by zepfietje** [comment] 2023-08-02 07:06
> Like this?
> 
> ```css
> .fi-select-input > option {
>    @apply dark:bg-gray-900;
> }
> ```

I suppose yeah.

> can't test it.

Could you create a custom theme and apply this styling in a CSS file?
A fix has to be confirmed for us to merge into core.

**Comment by chrisreedio** [comment] 2023-08-02 08:37
![image](https://github.com/filamentphp/filament/assets/77644584/668809ea-b2b8-4aeb-817c-08bbe392d23a)

I have just tested this via a custom theme and it does fix the issue.

Edit: Running Chrome on Windows 10.

**Comment by zepfietje** [comment] 2023-08-02 08:53
Thanks for checking, @chrisreedio!
Is the border supposed to be so light by the way?

**Comment by chrisreedio** [comment] 2023-08-02 09:10
Not sure. 

I made a custom theme, and added only 

```css
.fi-select-input > option {
    @apply dark:bg-gray-900;
}
```
to the `theme.css`.

**Comment by zepfietje** [comment] 2023-08-02 09:21
Yeah not sure either as it's all browser magic.
At least options are readable and it looks ok.

I've applied a potential fix in https://github.com/filamentphp/filament/commit/a147ab6dbec2668e1b125f22b160dde75a87ddaf.
Could you pull in 3.x and verify it works indeed, @chrisreedio?

**Comment by chrisreedio** [comment] 2023-08-02 09:44
Sure.

Commented out the 'fix'.

```css
/*.fi-select-input > option {*/
/*    @apply dark:bg-gray-900;*/
/*}*/
```
Ran `npm run build`, and we're back to being broken. 

![image](https://github.com/filamentphp/filament/assets/77644584/c7538f5d-8534-4612-910e-1fd9b3550c2d)

Also disabled custom theme in `AdminPanelProvider.php`.

then `composer update` and we look good!

![image](https://github.com/filamentphp/filament/assets/77644584/52db3f15-7829-43f7-86d1-ec14f654ecbd)


This is on the latest version pushed to 3.x-stable.


Thanks @zepfietje for getting this into the repo! 🚀

**Comment by mtsunu** [comment] 2023-08-02 09:48
Yes it works.

![image](https://github.com/filamentphp/filament/assets/4941448/e1a1bd13-a162-429b-99a1-60d88f0c66ca)

on Edge on Windows 11

**Comment by zepfietje** [comment] 2023-08-02 10:06
Thanks for your help on this one everyone!

**Comment by qcol** [comment] 2023-08-02 10:31
Thanks, it works now! 

![image](https://github.com/filamentphp/filament/assets/358993/345125c0-c989-433e-93fb-6bb96e822c62)

**Comment by Jerry-Malaba** [comment] 2023-09-01 16:49
i found this simple solution

Forms\Components\Select::make('type')
                            ->native(false)

**Comment by zepfietje** [comment] 2023-09-02 08:56
@Jerry-Malaba, this issue has already been fixed.
You can just use the native select.

**Comment by kombiahrk** [comment] 2023-10-19 08:30
how to solve issue for pagination select

**Comment by zepfietje** [comment] 2023-10-19 10:33
The fix to this issue should automatically be applied to the select input in the pagination component. If you're experiencing issues, please create a fresh bug report. 🙂
