### ISSUE TITLE
Wrapping Infolist RepeatableEntry in a Section/Grid/Group breaks relationship

### ISSUE THREAD

**Issue by ashleyhood** [laravel-filament/filament#9396] opened 2023-10-31 18:09 UTC
### Package

filament/filament

### Package Version

v3.0.88

### Laravel Version

v10.30.0

### Livewire Version

v3.0.8

### PHP Version

PHP 8.2.12

### Problem description

When using an Infolist for a resource that has a `Filament\Infolists\Components\RepeatableEntry` wrapped in a `Filament\Infolists\Components\Section`, nested inside a `RepeatableEntry` it causes the nested `RepeatableEntry` to only render the first record for each of the parent `RepeatableEntry`.

### Expected behavior

Each nested `RepeatableEntry` should render the correct record for the parent `RepeatableEnrty`.

This works as expected if you don't wrap the nested `RepeatableEntry` in a `Section/Grid/Group`. 

### Steps to reproduce

Wrap a nested `RepeatableEntry` in a `Section\Grid\Group` inside another `RepeatableEntry`.

### Reproduction repository

https://github.com/ashleyhood/filament-infolist-test

**Comment by zepfietje** [comment] 2023-11-01 15:22
Dupe of https://github.com/filamentphp/filament/issues/6964.

**Closed as not planned by zepfietje** 2023-11-01 15:22 UTC
Labels: bug, unconfirmed, low priority
