### ISSUE TITLE
Searchable select inputs records key pressed when navigating using arrow keys.

### ISSUE THREAD

**Issue by dks-adaptdigital** [laravel-filament/filament#10811] opened 2024-01-15 15:06 UTC
### Package

filament/forms

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

PHP 8.1

### Problem description

I was using arrow keys to navigate a form and fill it in. When I got to the select element, which is searchable, I noticed that it recorded the `arrowdown` keystroke and displayed it back to me in the UI.

https://github.com/filamentphp/filament/assets/132998782/0aca0b34-fe23-4efe-a638-0af6e53cc51e

### Expected behavior

I would expect the select element to not show me which key(s) I have pressed to select an option.

### Steps to reproduce

1. Clone down the repro repository provided.
2. Set up the application (I used sail) and run it locally.
    * setup your local db
    * composer install
    * npm install
    * npm run dev
3. Navigate to the dummies resource and click create new.
4. Tab to the select input and press down.

### Reproduction repository

https://github.com/dks-adaptdigital/filament-arrowdown-repro

**Comment by danharrin** [comment] 2024-01-15 20:18
Duplicate of #5707, https://github.com/Choices-js/Choices/issues/1080

**Comment by danharrin** [comment] 2024-01-15 20:18
Using tabs to navigate between fields should work fine

**Closed as not planned by danharrin** 2024-01-15 20:18 UTC
Labels: bug, unconfirmed, low priority

**Comment by dks-adaptdigital** [comment] 2024-01-16 09:45
Apologies @danharrin I missed this when scanning through previous issues.
