### ISSUE TITLE
Select input in action modals

### ISSUE THREAD

**Issue by tareq-alqadi** [laravel-filament/filament#9052] opened 2023-10-12 12:24 UTC
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

An error occurred when i am using a select input inside an create, edit, or view action.
At the first time i am open the action modal everything works fine, but when i am closing this modal error occurred in console.
![image](https://github.com/filamentphp/filament/assets/70425045/ee5e3923-8760-445f-b629-0bf3f979f77f)

after this error occurred and i am quickly trying to open this modal again it's not working and modal not opened, but after few moments it's works fine and the problem repeated again.

### Expected behavior

This problem should not appearing.

### Steps to reproduce

Just install a fresh Laravel and filament project and put a non native select inside a action modal.

### Reproduction repository

https://github.com/tareq-alqadi/testSelect.git

**Comment by zepfietje** [comment] 2023-10-12 13:04
Please search existing issues before creating a bug report.
Duplicate of https://github.com/filamentphp/filament/issues/8234.

**Closed as not planned by zepfietje** 2023-10-12 13:04 UTC
Labels: bug, unconfirmed, low priority
