### ISSUE TITLE
DatePicker behaves differently on first and subsequent selection for dependent date field with max date

### ISSUE THREAD

**Issue by citroid** [laravel-filament/filament#5808] opened 2023-02-28 10:00 UTC
### Package

filament/filament

### Package Version

v2.17.4

### Laravel Version

v9.52.4

### Livewire Version

v2.12.0

### PHP Version

PHP 8.1.12

### Problem description

A form for a Filament resource contains two fields with dependent DatePicker elements: event_date and arrival_date.
Field event_date is reactive and and should automatically update the value of the max date constraint for the field arrival_date (the logic is: the arrival_date for the chosen event_date cannot be later than one day before the event_date).

After selecting an event_date the DatePicker of arrival_date offers **up to two days before** the selected event_date. 
However, **on all subsequent selections** the DatePicker correctly offers dates **up to one day before** the selected event_date.

This behaviour is inconsistent and happens only on the first attempt to select a date on the dependent DatePicker.

### Expected behavior

The DatePicker element of the dependent date field should offer the same (and correct) max date on all selections of a value and not behave differently on the first selection.

### Steps to reproduce

1. I select a value for event date (e.g. 26.05.2023)
2. When I select the arrival date for the first time the maximum allowed value is two days before event date (e.g. 24.05.2023)
3. After selecting an arrival date for the first time, I try to pick a different date and on the second time entering the DatePicker it now offers me the day before event date as maximum (e.g. 25.05.2023)

Relevant source code of the EventResource's `form()` function from the reproduction repo:
```
DatePicker::make('event_date')
                    ->label('Event Date')
                    ->displayFormat('d.m.Y')
                    ->closeOnDateSelection()
                    ->minDate(now())
                    ->reactive()
                    ->required(),
DatePicker::make('arrival_date')
                    ->label('Arrival Date')
                    ->displayFormat('d.m.Y')
                    ->closeOnDateSelection()
                    ->minDate(now())
                    ->maxDate(function (callable $get) {
                        // Calculate max of arrival date depending on event date
                        $eventDate = $get('event_date');
                        if ($eventDate == null) {
                            Log::info("Retrieved value of event_date is null.");
                            return null;
                        } else {
                            Log::info("Retrieved value of event_date: " . Carbon::parse($eventDate)->toDateString());
                            Log::info("Set maxDate for 'arrival_date' to: " . Carbon::parse($eventDate)->subDays(1)->toDateString());
                            return Carbon::parse($eventDate)->subDays(1);
                        }
                    }),
```

### Reproduction repository

https://github.com/citroid/filamentphp-datepicker2

**Comment by zepfietje** [comment] 2023-02-28 11:47
I think this is a duplicate of https://github.com/filamentphp/filament/issues/5601.

Let me know if it's not and I'll reopen this issue, @citroid.

**Comment by danharrin** [comment] 2023-02-28 13:59
Just keeping this open for another reproduction repo when I get round to that issue

**Comment by danharrin** [comment] 2023-03-02 22:51
Hey! I've tracked the bug down and pushed a fix. It'll be available in the next release. Let me know if it doesn't work for you.

**Closed as completed by danharrin** 2023-03-02 22:51 UTC
Labels: bug, unconfirmed

**Comment by citroid** [comment] 2023-03-03 08:03
Many thanks for that!
I'll check it out when the update becomes available and will report if the problem is solved.
BTW: I had no intention of opening a duplicate here. I also saw the other[ issue](https://github.com/filamentphp/filament/issues/5601) but was not sure if it actually has the same cause (there are some obvious similarities like the DatePicker value unexpectedly jumping for one day, but also differences in how the component is being used as my issue involves a max date constraint and doesn't make explicit use of timezones). But I think it definitely makes sense to verify if the fix for one of those issues actually solves both of them.

**Comment by danharrin** [comment] 2023-03-03 09:55
Hey! The update was already released last night. And just FYI, theyre completely different issues.

**Comment by citroid** [comment] 2023-03-03 10:17
I checked the latest release notes and didn't find it there, but I should have taken a look at the full change log...
The good news is I just updated my dependencies to the latest version and can confirm that it is now working as expected (the max date is now correct on the first selection attempt and remains stable on subsequent selection attempts).
Again thanks for the quick resolution!
