### ISSUE TITLE
Toggle doesn't honor `disabled()`

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#7370] opened 2023-08-02 03:35 UTC
### Package

filament/filament

### Package Version

v3.0.2

### Laravel Version

v10.17

### Livewire Version

v3-beta

### PHP Version

8.2

### Problem description

[Screencast from 08-02-2023 10:33:38 AM.webm](https://github.com/filamentphp/filament/assets/28250303/38a0b8cb-93ff-41f2-88a7-98bf0d1c099b)
As we can see from vide, toggle is not 'disabled' in view page (modal)

### Expected behavior

Cannot toggleable

### Steps to reproduce

Clone
Install
migrate --seed
Check user resource

### Reproduction repository

https://github.com/valpuia/v3-datetimepicker-bug

**Comment by maharsh-mangal** [comment] 2023-08-02 06:15
@valpuia Hello, can i open a PR for this?

**Comment by valpuia** [comment] 2023-08-02 06:46
> @valpuia Hello, can i open a PR for this?

Yes sure.. This behaviour also happens in View page, not modal.. make sure you check both

**Comment by zepfietje** [comment] 2023-08-02 07:15
Thanks for reporting, duplicate of https://github.com/filamentphp/filament/issues/7093.

**Comment by zepfietje** [comment] 2023-08-21 07:36
Do you have any idea what might be the cause of this, @sakanjo?
The toggle component uses a `<button>` under the hood.
Could it be that Livewire handles those differently from inputs?

**Comment by zepfietje** [comment] 2023-08-21 07:43
@danharrin, do you have any idea (since you've been following along on that Livewire PR)?

**Comment by sakanjo** [comment] 2023-08-21 08:44
@zepfietje The PR did the job,  The livewire version used in this repo isn't the latest version.

@valpuia can you please confirm this issue on livewire version `v3.0.0-beta.10`

**Comment by valpuia** [comment] 2023-08-21 09:25
I install new laravel and filament and I cannot get this error anymore, so confirmed as fixed.
Filament: `filament/filament (v3.0.27)`
Livewire: `livewire/livewire (v3.0.0-beta.10)`

[Screencast from 08-21-2023 04:23:02 PM.webm](https://github.com/filamentphp/filament/assets/28250303/289e253d-92cf-41fd-ad0c-ed34b69c46de)

**Comment by zepfietje** [comment] 2023-08-21 09:47
Hmm, for some reason it doesn't work when you disable the toggle on the products edit page of the demo though.

**Comment by zepfietje** [comment] 2023-08-21 09:48
Could you have a look, @sakanjo?
I'm failing to understand why it seems to work in your case and not in the case I mentioned.

**Comment by sakanjo** [comment] 2023-08-21 20:46
@zepfietje Really weird stuff going there, plus the toggle button flickers when sending a request,

the main problem is when sending a request it will re-set the disabled to true but when the request is resolved it removes it which is correct when using `wire:loading.attr`

I will think in a solution since this bug only affects `Toggle` which even more weird,

One of the easy solutions is:
```diff php
- 'disabled' => $isDisabled(),
- 'wire:loading.attr' => 'disabled',
+ ...($isDisabled() ? ['disabled' => $isDisabled()] : ['wire:loading.attr' => 'disabled'])
```

**Comment by zepfietje** [comment] 2023-08-24 09:13
Hmm but isn't that exactly what was solved by the Livewire PR for other components, @sakanjo?

**Comment by sakanjo** [comment] 2023-08-24 09:20
@zepfietje that should be, i will try to fix it again

**Comment by zepfietje** [comment] 2023-08-24 09:26
Perfect. Let us know your findings, @sakanjo! 🙏

**Comment by sakanjo** [comment] 2023-08-24 20:54
@zepfietje After hours of debugging i came to know why this is happening,
when using wire:model it's automatically setting `wire:target` to it's name according to [wire-loading#150](https://github.com/livewire/livewire/blob/main/js/directives/wire-loading.js#L150), now for buttons since we can't use wire:model, wire:target is not set that's what causing the problem on [wire-loading#68](https://github.com/livewire/livewire/blob/main/js/directives/wire-loading.js#L68) the targets length is 0 and by which startLoading is called,
now you might say well why this is only happening on the demo edit page, the answer because on the edit page we are using lazy data fetching fields `SpatieMediaLibraryFileUpload` and `preload` and ... which causing second request to be sent,

Now to solve this we can set wire:target on ToggleComponent to the parent form, in **edit page** case it's **save** and in **create page** case it's **create** and in other pages as well, which will set the target by [wire-loading#145](https://github.com/livewire/livewire/blob/main/js/directives/wire-loading.js#L145).

Hope this helps, sorry if i missed something or didn't explain the problem very well, feel free to ask further questions.

**Comment by wychoong** [comment] 2023-08-29 08:49
just to comment here confirm having the same issue when using `SpatieMediaLibraryFileUpload` field.

Filament v3.0.34  
Livewire v3.0.1

**Comment by zepfietje** [comment] 2023-08-29 11:41
Could you open a separate issue, @wychoong?

**Comment by wychoong** [comment] 2023-09-02 08:11
> Could you open a separate issue, @wychoong?

done #8236

**Comment by zepfietje** [comment] 2023-09-02 08:59
Oh that actually looks like the same bug?
I thought you referred to a file upload bug, but you meant using a toggle in a form with that other field.

**Comment by wychoong** [comment] 2023-09-02 09:04
> Oh that actually looks like the same bug? I thought you referred to a file upload bug, but you meant using a toggle in a form with that other field.

could be the same bug. but the repo used in this issue is with date picker, and I'm having the issue with Spatie image field.
but looking at sakanjo's analysis could be the same root cause

**Comment by danharrin** [comment] 2023-09-10 10:09
Thanks for your explanation @sakanjo, I was able to fix this very easily thanks to that

#8383

**Closed as completed** 2023-09-10 10:08 UTC
Labels: bug, confirmed, high priority
