### ISSUE TITLE
Fileupload: Second drop breaks FileUpload

### ISSUE THREAD

**Issue by nim0kkruse** [laravel-filament/filament#8490] opened 2023-09-14 10:41 UTC
### Package

filament/filament

### Package Version

3.0.48

### Laravel Version

10.23.1

### Livewire Version

3.0.3

### PHP Version

8.2.10

### Problem description

If we have a simple FileUpload form field we cant drop two pdf files. If we drop the first everything is ok. On the second drop the first file and the second one are removed and the loading spinner in the submit button of the form won't stop spinning.

### Expected behavior

It should be possible to drop two seperate files without the field to be broken.

### Steps to reproduce

1. Create a Ressource with a fileupload field
2. visit the create page
3. drop one pdf file
4. drop a second file after successful upload of the first file
-> Field ist broken

### Reproduction repository

https://github.com/KriKrus/filament-fileupload-drop-bug

### Relevant log output

```shell
No logged errors in laravel.log or browser console
```

**Comment by nim0kkruse** [comment] 2023-09-14 10:47
Example as video: 
[drop_bug.webm](https://github.com/filamentphp/filament/assets/115444441/f47acfdf-e109-41af-b772-964d26e60a3c)

**Comment by danharrin** [comment] 2023-09-14 10:47
`multiple()`?

**Comment by nim0kkruse** [comment] 2023-09-14 10:47
Setting mutiple() or not won't change the behaviour

**Comment by danharrin** [comment] 2023-09-14 10:48
I dont understand, do you want 2 files stored at once. Or are you replacing the first file with the second file

**Comment by nim0kkruse** [comment] 2023-09-14 10:50
It would be replacing the first file. Problem is, that both files wont be in the field after the second drop

**Comment by danharrin** [comment] 2023-09-14 11:01
Duplicate of #6775 then

**Closed as not planned by danharrin** 2023-09-14 11:01 UTC
Labels: bug, unconfirmed, low priority
