### ISSUE TITLE
Wizard / Multistep fields disappearing on previous step

### ISSUE THREAD

**Issue by clinvest** [laravel-filament/filament#10441] opened 2023-12-22 16:08 UTC
### Package

filament/filament

### Package Version

v3.1.26

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.0

### Problem description

On a wizard field, when going back to a previous step, the fields disapear.

### Expected behavior

Fields shouldn't disappear.

### Steps to reproduce

- Get the projet
- Go to http://127.0.0.1:8000/admin/users
- Click on the table list action "wizard"
- Click on "next"
- Click on "previous"
- Name field disappeared

### Reproduction repository

https://github.com/clinvest/filament-issue

**Comment by zepfietje** [comment] 2023-12-22 16:14
Duplicate of https://github.com/filamentphp/filament/issues/10429.

**Closed as not planned by zepfietje** 2023-12-22 16:14 UTC
Labels: bug, unconfirmed, low priority
