### ISSUE TITLE
When widget lazy loading, the widget cannot get the correct height.

### ISSUE THREAD

**Issue by panlatent** [laravel-filament/filament#14315] opened 2024-09-21 09:26 UTC
### Package

filament/filament

### Package Version

v3.2.113

### Laravel Version

11.9

### Livewire Version

v3.2.113

### PHP Version

8.2.22

### Problem description

When the widget is lazy loaded, the height of the section element that wraps it is set to 8rem. After the widget is displayed, the section still maintains this height, which causes the widget content to overflow.

This problem does not occur when $isLazy is false

### Expected behavior

-------

### Steps to reproduce

-------

### Reproduction repository (issue will be closed if this is not valid)

-------

**Comment by markdynamo6** [comment] 2024-09-22 05:29
Is this fixed, as I'm am now experiencing the same.

**Comment by mark-nicepants** [comment] 2024-09-22 08:19
Same after running `composer update` my widgets with charts are broken.

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/22ebb682-f7fa-4abf-9c14-476320d5b20a">

**Comment by mark-nicepants** [comment] 2024-09-22 08:25
Also confirmed that setting "isLazy" to true will fix the incorrect height for now.

**Comment by lloricode** [comment] 2024-09-22 13:04
same as mine

![Screenshot from 2024-09-22 21-04-01](https://github.com/user-attachments/assets/759d3ea4-333c-455c-acff-6ee6bf68c10e)

**Comment by vanhooff** [comment] 2024-09-22 17:11
@danharrin Can you please reopen this? I am having the same issue as mentioned above. The cause is probably this [Livewire update](https://github.com/livewire/livewire/releases/tag/v3.5.7). 

A temporary workaround is to put this in the root of your composer.json

```
"conflict": {
    "livewire/livewire": "3.5.7 || 3.5.8"
},
```
and then...
```
composer update
```
This will prevent composer from installing 3.5.7 || 3.5.8, but not lock it to a specific version.

**Comment by aeq-dev** [comment] 2024-09-23 08:53
Same issue here

**Comment by danharrin** [comment] 2024-09-23 14:10
Thanks for letting me know, the latest release of Filament is locked to max Livewire [v3.5.6](https://github.com/livewire/livewire/releases/tag/v3.5.6). Please let me know if this doesn't solve it.

I do not have time to investigate and report this issue to Livewire, so I would appreciate it if someone reading this would do so on our behalf. Many thanks.

**Comment by danharrin** [comment] 2024-09-23 14:15
Looks like people are reporting style issues in livewire/livewire#8870, and we use the style property to add height to charts. Maybe that's a good place to start

**Comment by jackwh** [comment] 2024-09-23 17:57
I see the earlier comments are on a merged PR, I filed a bug here so it doesn't get missed: https://github.com/livewire/livewire/discussions/8881

**Comment by francoism90** [comment] 2024-09-24 10:11
The buttons also seems to be broken now.

I think the style is isn't parsed on the correct time/moment.

**Comment by leandrocfe** [comment] 2024-09-24 11:58
https://github.com/livewire/livewire/pull/8883

**Comment by zepfietje** [comment] 2024-10-11 09:28
This issue is fixed with the latest Livewire release: https://github.com/filamentphp/filament/pull/14497.

**Closed as completed** 2024-10-11 09:38 UTC
Labels: bug in dependency, high priority

**Comment by drsdre** [comment] 2025-02-03 11:12
![Image](https://github.com/user-attachments/assets/b87f3a6d-56a4-4ce8-b4d9-e088d1afeaf9)

Using the latest Filament version 3.2.136 on Laravel 11.41.3 with Livewire stuck on 3.5.12 (because filament/support requires 3.5.12), the original issue with graphs exceeding the widget area seems to be back again.
