### ISSUE TITLE
the 'notificationsSent' event is not being fired on the production server.

### ISSUE THREAD

**Issue by mateusgalasso** [laravel-filament/filament#14841] opened 2024-11-19 02:19 UTC
### Package

filament/filament

### Package Version

v3.2.124

### Laravel Version

11

### Livewire Version

v3.0.0

### PHP Version

PHP 8.3.9

### Problem description

the 'notificationsSent' event is not being fired on the production server.
I was unable to reproduce it locally.
Does anyone have any ideas?

My local after save resource
<img width="2026" alt="image" src="https://github.com/user-attachments/assets/272eb63c-7208-4593-bd3b-3835f2fde76b">

On server after save resource
<img width="2040" alt="image" src="https://github.com/user-attachments/assets/d0b89c9b-050c-434b-83d7-37c44b70a73d">

### Expected behavior

dispatch 'notificationsSent' event

### Steps to reproduce

I was unable to reproduce it in the local environment

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/mateusgalasso/filament

**Comment by yassir3wad** [comment] 2024-11-19 08:39
Exact same issue happening with me. I do have the following code on my service provider
```php
         Page::$reportValidationErrorUsing = function (ValidationException $exception) {
                    Notification::make()
                        ->title($exception->getMessage())
                        ->danger()
                        ->color('danger')
                        ->send();
                };
```

And in local env it show the toast/notification after submit, but in development env it's not dispatching any event after submit, instead it showing the toast once the page is refreshed. I guess the issue is related to sessions.

I'm using latest versions of all laravel, PHP, filament, and my dev env running over Vapor.

**Comment by mikwiat** [comment] 2024-11-19 19:04
We are experiencing exactly the same as @yassir3wad. I start to suspect that this is an issue in Livewire. Anyone experiencing the same?

**Comment by zepfietje** [comment] 2024-11-20 11:14
Has this issue come up recently?
If so, please point me at the exact version of Filament and Livewire that caused this regression.

**Comment by twarkie** [comment] 2024-11-20 11:18
> We are experiencing exactly the same as @yassir3wad. I start to suspect that this is an issue in Livewire. Anyone experiencing the same?

I work at the same company and we have the same problem on multiple projects. All are served with FrankenPHP.

After some investigation we found that the issue is caused by an empty `X-Livewire` header. Empty headers are removed in our production environment. 

This fix works: https://github.com/livewire/livewire/discussions/8333
```
document.addEventListener('livewire:initialized', () => {
    Livewire.hook('request', ({ options }) => {
        options.headers['X-Livewire'] = true;
    });
});
```

But something has to have changed recently? I really think we would have noticed a problem like this earlier otherwise. But probably a change in Livewire.

**Comment by zepfietje** [comment] 2024-11-20 11:26
Can't find anything related to this that has changed in Livewire recently.
Also nothing has changed regarding notifications in Filament, so I'm going to close this issue here.

**Closed as not planned by zepfietje** 2024-11-20 11:26 UTC
Labels: bug, unconfirmed, medium priority

**Comment by mateusgalasso** [comment] 2024-11-20 11:33
> > We are experiencing exactly the same as @yassir3wad. I start to suspect that this is an issue in Livewire. Anyone experiencing the same?
> 
> I work at the same company and we have the same problem on multiple projects. All are served with FrankenPHP.
> 
> After some investigation we found that the issue is caused by an empty `X-Livewire` header. Empty headers are removed in our production environment.
> 
> This fix works: [livewire/livewire#8333](https://github.com/livewire/livewire/discussions/8333)
> 
> ```
> document.addEventListener('livewire:initialized', () => {
>     Livewire.hook('request', ({ options }) => {
>         options.headers['X-Livewire'] = true;
>     });
> });
> ```
> 
> But something has to have changed recently? I really think we would have noticed a problem like this earlier otherwise. But probably a change in Livewire.

It worked and saved my life, thank you.
I love this community ❤️

**Comment by asciito** [comment] 2025-10-06 01:10
Don't know if this help someone else, but I was having the same problem with my production site on Laravel Cloud, and my problem was related with the cookies, because the amount of data store in the cookie was too large, so I just change the `SESSION_DRIVER` from `cookie` to `database.

<img width="838" height="54" alt="Image" src="https://github.com/user-attachments/assets/7ad407ad-ddc4-4bfe-8044-982942303c7f" />

**Comment by dasundev** [comment] 2025-10-24 16:47
@asciito we are experiencing the same warning with the `cookie` driver. when the table I am updating has fewer columns, I receive the notification and no console warning appears. However, if the table has many columns, the cookie size increases and the notification is no longer sent BUT everything works when set `SESSION_DRIVER` to `database` driver.

cc: @zepfietje @danharrin
