### ISSUE TITLE
Action arguments are empty

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-filament/filament#9444] opened 2023-11-03 15:44 UTC
### Package

filament/actions

### Package Version

v3.0.89

### Laravel Version

v10.30.1

### Livewire Version

v3.0.10

### PHP Version

8.2

### Problem description

Action arguments are empty on a `live()` action on the standalone form component is triggered.

### Expected behavior

The arguments for a standalone action needs to be passed when a `live()` action on a form component is triggered.

### Steps to reproduce

Here is the code for the accessing the arguments for the standalone form
https://github.com/abishekrsrikaanth/filament-test/blob/main/app/Http/Livewire/StandaloneAction.php#L29

When you choose an element from the `Select` element in the `form`, the `$arguments` on the `form()` method is empty.

### Reproduction repository

https://github.com/abishekrsrikaanth/filament-test/

**Comment by zepfietje** [comment] 2023-11-04 11:19
Dupe of https://github.com/filamentphp/filament/issues/8763.

**Closed as not planned by zepfietje** 2023-11-04 11:19 UTC
Labels: bug, unconfirmed, low priority
