### ISSUE TITLE
Group schema with closure inside Repeater does not pass $get

### ISSUE THREAD

**Issue by elasti-co** [laravel-filament/filament#5838] opened 2023-03-03 00:42 UTC
### Package

filament/filament

### Package Version

^v2.17.9

### Laravel Version

v10.1

### Livewire Version

v2.0

### PHP Version

PHP 8.2

### Problem description

Group schema inside Repeater when filled with closure does not pass \Closure $get attributes. Instead it returns NULL.

### Expected behavior

Like in 2.17.8 and before, it had passed $get parameters of the form.

### Steps to reproduce

``` php
Forms\Components\Repeater::make('users')
    ->schema([
        Forms\Components\TextInput::make('name')->reactive(),
        Forms\Components\Group::make()
            ->schema(function (\Closure $get) {
                // TODO Fix $get (now it returns NULL)
                return [
                    Forms\Components\TextInput::make('password')
                        ->visible($get('name') === 'John'),
                ];
            }),
    ]),
```

### Reproduction repository

https://github.com/elasti-co/filament_bug

**Comment by danharrin** [comment] 2023-03-03 07:42
Please update your Filament version as I think we fixed this

**Comment by elasti-co** [comment] 2023-03-03 08:03
> Please update your Filament version as I think we fixed this

Dan, thank you for filament and reply ) 
Checked version 2.17.10. Still not working. Maybe 2.17.11 will do, but it's not yet available in composer.

**Comment by danharrin** [comment] 2023-03-03 09:59
Ah that's weird, looks like our GitHub actions failed to release. It should be available in Composer now

**Comment by elasti-co** [comment] 2023-03-03 10:28
Yeah, now it's available in Composer. Updated.

But still face the problem...
The latest version it worked was 2.17.8.

**Comment by danharrin** [comment] 2023-03-04 00:20
Fixed by #5845, let me know if not

**Closed as completed** 2023-03-04 00:19 UTC
Labels: bug, unconfirmed

**Comment by elasti-co** [comment] 2023-03-04 09:54
@danharrin Thank you, now it works 🤩

**Comment by MaciejLunitz** [comment] 2025-01-23 09:13
Laravel 10.48, Filament 3.2, January 2025
I still couldn't pass $get in the Repeater schema until I found this issue yesterday.
Thanks to @elasti-co and his top post I have tried to put my schema inside the Group. And there $get is passing through the function.

I haven't found any other discussion or docs for this case. Even Copilot suggests wrong way (directly in schema).

@danharrin, should it work (to pass $get) directly in Repeater schema, or not?

**Comment by danharrin** [comment] 2025-01-23 13:12
@MaciejLunitz please open an issue with a reproduction repository and it will be investigated in due course
