### ISSUE TITLE
Stats chart color incorrect and inconsistent between refreshes when two different colors are used

### ISSUE THREAD

**Issue by npbreland** [laravel-filament/filament#11515] opened 2024-02-21 17:31 UTC
### Package

filament/filament

### Package Version

v3.2.35

### Laravel Version

v10.45.0

### Livewire Version

v3.4.6

### PHP Version

PHP 8.3.2

### Problem description

When displaying a StatsOverview widget with two charted stats where the colors are meant to differ, _both_ stats take on only one of the colors, and the color seems to randomly alternate between the two between refreshes.

### Expected behavior

I expect the color for each chart to be what I specified in the code.

### Steps to reproduce

Create a custom StatsOverview widget with two stats, each of which has a chart. Set the colors of these two charts to be different (e.g. one 'success', one 'danger'). View the displayed widgets in the UI, and see that one of the colors is not correct.  Refresh several times and see that the colors sometimes alternate. (In the reproduction repository, it's all done for you. Just go the dashboard page.)

### Reproduction repository

https://github.com/npbreland/filament-stats-bug

**Comment by zepfietje** [comment] 2024-02-28 11:17
Interesting...
So it seems like getting the color element ref doesn't work reliably?

I have no idea why it would sometimes go outside the current stat Alpine component and pick a sibling value though.

Any ideas?

https://github.com/filamentphp/filament/blob/427186fce4de7092134f403a56f789b6e7a4f976/packages/widgets/resources/js/components/stats-overview/stat/chart.js#L45

**Comment by npbreland** [comment] 2024-03-01 16:22
Hi @zepfietje, thanks for your reply. I haven't had time to investigate this further, but I did notice that the behavior seems to be inconsistent between browsers. This issue happens consistently in the Brave browser, but on base Chromium and Chrome I don't see this consistently. I find this quite odd because my version of Brave and Chromium are on the same version of Chromium: 122.0.6261.94

However, on the Chrome and Chromium the issue consistently arises upon resizing the window. When that happens I just refresh, and the issue goes away. Very interesting indeed :sweat_smile:

**Comment by danharrin** [comment] 2024-03-10 19:58
Hi, sorry but I am going to close this. Simply because it is so inconsistent makes it difficult to track down. Brave might be doing something funky there, I'm glad you can't reproduce in more mainstream browsers. I'd welcome any PRs with your findings, or if you comment further and let us know how to consistently trigger this issue in plain Chromium, I will reopen the issue.

**Closed as not planned by danharrin** 2024-03-10 19:58 UTC
Labels: bug, unconfirmed, low priority
