### ISSUE TITLE
ActionGroup changes height of table rows

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel-filament/filament#7171] opened 2023-07-23 23:43 UTC
### Package

filament/filament

### Package Version

v3.0.0-beta7

### Laravel Version

v10.15.0

### Livewire Version

v3.0.0-beta3

### PHP Version

8.2.7

### Problem description

Table rows with `ActionGroup`s are quite a bit larger than those without:

<img width="1251" alt="image" src="https://github.com/filamentphp/filament/assets/18192441/61d81ba8-0e37-4edb-a11e-5931282142d5">

This happens in v2 as well.

### Expected behavior

Table rows should always be the same height.

### Steps to reproduce

Create any `ActionGroup`, e.g.:

```php
// app/Filament/Resources/UserResource.php

public static function table(Table $table): Table
{
    return $table
        ->columns([
            TextColumn::make('name'),
        ])
        ->actions([
            EditAction::make(),
            ActionGroup::make([
                DeleteAction::make(),
            ])->visible(fn () => (bool) random_int(0, 1)),
        ]);
    }
```

### Reproduction repository

https://github.com/bakerkretzmar/filament-issue-reproduction

**Comment by zepfietje** [comment] 2023-07-24 07:18
This is probably caused by the tap target of the action group trigger icon button.
The tables package is still pending redesign, so I'll close this issue as it'll probably be handled when I'm working on revamping the tables package (which is now).

Thanks for bringing this to our attention!

**Comment by bakerkretzmar** [comment] 2023-09-09 01:47
@zepfietje this issue is still present in v3.0.41, is the redesign still in progress or should this be reopened?

**Comment by zepfietje** [comment] 2023-09-15 09:25
I'll reopen this as icon button actions seem to increase the table row height indeed.
This is intended for link and button actions, but maybe icon buttons should be treated differently (by potentially adding a negative y margin).

**Comment by bakerkretzmar** [comment] 2023-09-15 14:02
Thanks! That's how I fixed this locally for now yeah, negative margin of 0.5rem on `.fi-ac-icon-btn-group`.

**Comment by zepfietje** [comment] 2023-12-04 14:23
This has been fixed some time ago already.

**Closed as completed by zepfietje** 2023-12-04 14:23 UTC
Labels: bug, confirmed, ui
