### ISSUE TITLE
Repeater field issues when adding items if the repeater has a TextInput with a mask

### ISSUE THREAD

**Issue by martink635** [laravel-filament/filament#5976] opened 2023-03-20 09:15 UTC
### Package

filament/filament

### Package Version

v2.17.17

### Laravel Version

v10.4.1

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.3

### Problem description

If using a simple resource (or a simple resource in a relation manager) and having a Repeater field with a TextInput that has a mask, the add items is not working as expected.

When opening the modal for the first time, everything works as expected. You add a new item and 1 is being added. After closing the dialog and editing the same resource, clicking add, adds multiple items at once. 

This can also be reproduced by first editing a resource (opens a modal), closing it, and trying to create a new resource. Clicking add items in the repeater field will add multiple items.

### Expected behavior

The expected behaviour is when you click add items in a repeater, that only 1 item is added to the list.

### Steps to reproduce

Sample reproduction code:

```php
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->required(),
                Forms\Components\Repeater::make('items')
                    ->schema([
                        TextInput::make('name')->required(),
                        TextInput::make('quantity')
                            ->mask( // Commenting this out, will make it work
                                fn (TextInput\Mask $mask) => $mask
                                    ->numeric()
                            ),
                        Select::make('role')
                            ->options([
                                'member' => 'Member',
                                'administrator' => 'Administrator',
                                'owner' => 'Owner',
                            ])
                            ->required(),
                    ])
                    ->columns(2),
            ]);
    }
```

### Reproduction repository

https://github.com/martink635/filamentphp-repeater-issue-reproduction

**Comment by danharrin** [comment] 2023-03-20 11:37
Duplicate of #1624 and #2291. We will attempt to fix this in v3 but for now, you cannot use a mask within a repeater.

**Closed as not planned by danharrin** 2023-03-20 11:37 UTC
Labels: bug, unconfirmed
