### ISSUE TITLE
MultiTenancy menu to limit the no of tenants shown with filter text widget

### ISSUE THREAD

**Issue by declum** [laravel-filament/filament#11771] opened 2024-03-08 17:45 UTC
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.0

### PHP Version

8.2

### Problem description

When user is part of many teams, and we enable multi tenancy, the menu appears too big which requires scrolling to find. (we have a bug for this scroll in mobile view in issue [7830](https://github.com/filamentphp/filament/issues/7830))

### Expected behavior

We want the menu to limit the teams/tenant shown, and allow filters to search for team.

### Steps to reproduce

```
git clone https://github.com/declum/example-repo
cd example-repo
mv .env.example .env
php artisan migrate --seed <- This will also create [admin@admin.dev](mailto:admin@admin.dev) user with 100 teams (password is "password")
php artisan serve
```

### Reproduction repository

https://github.com/declum/example-repo

**Comment by danharrin** [comment] 2024-03-10 19:34
This just sounds like a feature request, can you take a screenshot of the visual bug with the menu getting cut off?

**Comment by declum** [comment] 2024-03-11 02:05
![1](https://github.com/filamentphp/filament/assets/22226/d895b934-9bb7-428b-b274-0784c388d8fe)
![2](https://github.com/filamentphp/filament/assets/22226/85951406-6b0b-4cb8-b1e3-8cd1bbc5004e)
Attached.

Menu doesnt scroll.

Here two things.

1 is a bug where the menu is not scrolling
2 is a feature request if we can limit the shown items, and allow the search option to pick the team without involving scrolling.

**Comment by danharrin** [comment] 2024-03-11 08:48
FYI - the issue will be closed when the bug is fixed, feature requests belong in Discussions or you can PR it yourself.

**Comment by zepfietje** [comment] 2024-03-11 15:25
Isn't this just a duplicate of https://github.com/filamentphp/filament/issues/10915?

**Comment by danharrin** [comment] 2024-03-11 17:00
@zepfietje similar, but this one will be closed when we make the dropdown scrollable. We will use the "size" feature of Floating UI, Adam is going to handle it when he has time.

**Comment by awcodes** [comment] 2024-03-12 00:39
Should I worry about the searchable or just the scrollable?

**Comment by awcodes** [comment] 2024-03-12 00:40
I can see this applying to other areas like filters too.

**Comment by danharrin** [comment] 2024-03-12 07:32
Just scrollable for now, the searchable is just a feature request

**Closed as completed** 2024-03-23 20:53 UTC
Labels: bug, unconfirmed, low priority, help wanted
