### ISSUE TITLE
Actions that `->requiresConfirmation()` 's notifications are run twice

### ISSUE THREAD

**Issue by dissto** [laravel-filament/filament#11099] opened 2024-01-26 21:38 UTC
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.00

### Livewire Version

v3

### PHP Version

PHP 8.3.0

### Problem description

An action (Filament\Actions\Action) with `->requiresConfirmation()` has trigger a notification via the `->action()` method causes the notification to run twice?!

I have attached a video that showcases it.

https://github.com/filamentphp/filament/assets/11778632/5e6b0576-62ba-49ed-af1e-d65296e6fc68

### Expected behavior

To not run twice

### Steps to reproduce

Just use the UserResource (edit a user) as an example. This repo is ready to run `migrate:fresh --seed` which seeds the user test@example.com with the default password.

### Reproduction repository

https://github.com/dissto/filament-actions-notifications-fire-twice

**Comment by danharrin** [comment] 2024-01-27 12:04
So I definitely don't think this is a case of them firing twice - they fire once, but you can still see the notification from the previous request as it hasnt transitioned out yet. I think there is a slight animation issue with transitioning new stacked notifications into view that creates a double request effect, so that could be investigated. But it's definitely low priority and doesn't really affect usability.

https://github.com/filamentphp/filament/assets/41773797/e45c5988-adb8-4a90-881c-f07bfaca1b6c

**Comment by beysach** [comment] 2024-01-31 10:28
I verified the existence of this issue through the use of the requiresConfirmation() function.

**Comment by beysach** [comment] 2024-01-31 11:10
To solve this problem I comment line 26 to 38 then notification started working normal without glitch effect.

vendor\filament\actions\resources\views\components\modals.blade.php
line 26


```php
            {{-- x-on:modal-closed.stop="
                const mountedActionShouldOpenModal = {{ \Illuminate\Support\Js::from($action && $this->mountedActionShouldOpenModal()) }}

                if (! mountedActionShouldOpenModal) {
                    return
                }

                if ($wire.mountedFormComponentActions.length) {
                    return
                }
               // $wire.unmountAction(false) is causing a problem.
                $wire.unmountAction(false)
            " --}}
```

**Comment by zepfietje** [comment] 2024-02-14 07:49
This issue is caused by notification animations being triggered by the Livewire request.

It happens in:
https://github.com/filamentphp/filament/blob/d9a34b36d4102625b0a91a9c2f9bff459dc6fc4d/packages/notifications/resources/js/components/notification.js#L71

The vertical notification animation has been broken since Livewire v3, and I haven't been able to fix it yet. Will close this issue as it's part of https://github.com/filamentphp/filament/issues/7395.

**Closed as not planned by zepfietje** 2024-02-14 07:49 UTC
Labels: bug, confirmed, ui, low priority

**Comment by ridhwansyah** [comment] 2025-08-02 15:27
https://drive.google.com/drive/folders/1_-4z0XfAZcsVu2j_uF4klnzJbK7GFWxg
The problem is at the 15 second.

Description:
I'm experiencing double notifications when performing bulk actions (Delete/Custom) on Filament Resources. Every time I execute a bulk action, the success notification appears twice.

Steps to Reproduce:
1. Open any Resource (Infak, Gallery)
2. Select multiple records
3. Click bulk action (Delete/Custom)
4. Confirm action
5. Notification appears twice

Expected: Single notification Actual: Double notification

- Filament: v3.3.31
- Laravel: Laravel Framework 12.2.0
- Livewire: v3.6.3
- PHP: PHP 8.4.5
- OS: Windows (Laragon)

Is there anyone who understands how to fix it? This is a global problem, according to Claude AI.


thank you to "beysach", alhamdulillah my project is now safe.
