### ISSUE TITLE
Wrong value in dependent select

### ISSUE THREAD

**Issue by Tryfciu** [laravel-filament/filament#13473] opened 2024-07-04 12:16 UTC
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v10.48.15

### Livewire Version

v3.5.2

### PHP Version

PHP 8.2.15

### Problem description

Hi. We are working on an app that is based purely on filament. In one form we have some nested/dependent selects. So we managed to bring it down to simple form to make it more understandable for you. We made a simple form which has 2 selects. `select1` - has single value
 `select2` - has 3/4 values; 4 values are present when `select1` has no chosen value, 3 values are present when `select1` has chosen value. Order or those options is random in both cases.
 
There is also one "hook" (afterStateUpdated) when option is being selected in `select1`. When this option is selected we want to manually (by `set()` method) set value of `select2` to `option2`.

The following code may show it better than my description:

 ```php
     public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Select::make('select1')->options([
                    'option1' => 'Option 1',
                ])->afterStateUpdated(function (Get $get, Set $set) {
                    // after option selection, change value of select2 to `option2`
                    $set('select2', 'option2');
                })
                ->live(),
                Select::make('select2')->options(function (Get $get) {
                    $select1Value = $get('select1');

                    // if select1 has no value then return following list
                    if($select1Value === null) {
                        return [
                            'option4' => 'Option 4',
                            'option3' => 'Option 3',
                            'option2' => 'Option 2',
                            'option1' => 'Option 1',
                        ];
                    }

                    // if select1 has value then return following list
                    return [
                        'option1' => 'Option 1',
                        'option2' => 'Option 2',
                        'option3' => 'Option 3',
                    ];
                })
            ]);
    }
```

### Expected behavior

So the case is following. When we enter form and then chose value in `select1` we would expect to see `option2` in `select2` because of the `afterStateUpdated` hook. But this does not happen. Instead of this in provided example we see `option3` as selected in `select2`. Therefore we treat this behaviour as incorrect.

We made some debugging and it turns out than under the hood, when we dump `$this->data`, the value is correct - it is set to `option2` BUT displayed value is `option3` as i mentioned before.

### Steps to reproduce

-- if you reproduce inside your own project

1. Setup empty resource
2. Paste provided code in created resource
3. Enter created form in a browser
4. Select value from `select1`

-- if you setup from reproduction repository

1. install dependencies
2. setup server `php artisan server`
3. enter `http://127.0.0.1:8000/examples`

### Related issues
We found some related issues eg. https://github.com/filamentphp/filament/issues/8972 but as most of them are closed/solved we belive it is somehow not fixed or this is a brand new problem.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Tryfciu/filament-issue

**Comment by zepfietje** [comment] 2024-07-12 12:38
Are you able to reproduce this issue in a Livewire project without Filament?
Asking since past issues were caused by Livewire.

**Comment by Tryfciu** [comment] 2024-07-12 16:34
I'm not into Livewire very much but I reproduced it as much as I could, and... it works as intended. For example with provided code when both selects are empty (initial) i choose `OPTION1` in 'select1' and value in 'select2' is resolved properly even though order of `select2` options changes meanwhile.

```php
class Counter extends Component
{
    public ?string $state = null;
    public ?string $city = null;
    
    public function render()
    {
        return view('livewire.counter');
    }

    public function states(): array {
        return [
            'OPTION0' => 'empty placeholder',
            'OPTION1' => 'Alaska 1',
        ];
    }

    public function cities(): array {
        if ($this->state === 'OPTION1') {
            return [
                'OPTION0' => 'empty placeholder',
                'OPTION1' => 'Birmingham 1',
                'OPTION2' => 'Montgomery 2',
            ];
        }

        return [
            'OPTION0' => 'empty placeholder',
            'OPTION2' => 'Montgomery 2',
            'OPTION1' => 'Birmingham 1',
        ];
    }

    public function changeCityToBirmingham(): void
    {
        $this->city = 'OPTION1';
    }
}
```
```blade
<div>
    {{$this->state}}
    {{$this->city}}
    
    <select wire:model.live="state" wire:change="changeCityToBirmingham">
        @foreach ($this->states() as $index => $state)
            <option value="{{ $index }}">{{ $state }}</option>
        @endforeach
    </select>

    <select wire:model.live="city" wire:key="{{$this->state}}">
        @foreach ($this->cities() as $index => $city)
            <option value="{{ $index }}">{{ $city }}</option>
        @endforeach
    </select>
</div>

```

**Comment by Tryfciu** [comment] 2024-07-12 21:17
Ok I managed to dive into source code of filament and basing on https://github.com/livewire/livewire/pull/6889 I found the way to solve this. Actually it is possible to make it work with current API. To solve issue following code must be added to `select2`.

```php
  ->extraAttributes(function (Get $get) {
      return ['wire:key', $get('select1')];
  })
```

Shall I open PR and add specific method to Select API to let users assign this value directly or is it not necessary?

**Comment by zepfietje** [comment] 2024-07-13 10:13
Thanks for looking into this, @Tryfciu.
Now I see it's indeed documented in the Livewire docs: https://livewire.laravel.com/docs/wire-model#dependent-select-dropdowns.

Since you can already work around it by manually adding a `wire:key`, I'm going to close this issue. I'll mention @danharrin though, so he can decide if this is something to improve in Filament.

**Closed as not planned by zepfietje** 2024-07-13 10:13 UTC
Labels: bug, unconfirmed, medium priority
