### ISSUE TITLE
Fix infolist section in repeatable entry showing first entry data for all entries if schema not in closure

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#6964] opened 2023-07-08 13:25 UTC

**Comment by danharrin** [comment] 2023-07-08 13:25
@zepfietje Please provide a reproduction

**Comment by zepfietje** [comment] 2023-07-08 14:44
Repo: https://github.com/zepfietje/filament-issue-6964
Issue commit: https://github.com/zepfietje/filament-issue-6964/commit/20aa83e439f290029b94901a6c5e61d15397f58d

1. Clone
2. Composer install
3. `php artisan key:generate`
4. `php artisan migrate`
5. `php artisan db:seed`
6. Go to `http://filament-issue-6962.test/admin/users/1`
7. Issue and reproduction steps / fix are described in a comment in the final commit

**Comment by phattarachai** [comment] 2023-08-18 22:52
Hi, I ran into this issue as well. 

If It is not fixed yet at least can you mention about this somewhere in the docs, so other people know to put closure inside schema function for now.

Thanks.

**Comment by zepfietje** [comment] 2023-08-19 09:30
We're not going to add notes to the docs for every bug, sorry.
It should just be fixed, simple as that.
Though we're really busy and this is relatively low priority, feel free to attempt a fix in a PR. 🙂

**Comment by fallback** [comment] 2023-08-23 12:40
Hey guys! 

Follow up on the issue, triggered from my [recent twit](https://twitter.com/DmytroSeredinov/status/1694278317317259390)
I've discovered, that this misbehaviour is refers to this line:

https://github.com/filamentphp/filament/blob/24fe227d68da7db6981c569926b55aadbe5f1a46/packages/infolists/src/Components/Concerns/HasState.php#L120

I'm not so confident yet in the lifecycle of Filament and wasn't imagined that there are a lot of different `HasState` traits being used with the Infopanel.
So when I comment that clause out (i.e., to avoid using the cachedFullStatePath), the Repeatable entries started to show real data they should show. 

I don't feel that I'm ready to create a PR, because of this `fix` wont fix the real root of an issue, but for anyone looking for some info, I believe, it might be useful.

Cheers!

**Comment by krekas** [comment] 2023-08-26 19:59
Can confirm that commenting out @fallback provided if statement fixes issue.

**Comment by mwagena** [comment] 2023-09-26 13:57
the issue is still there.. the fix mentioned above does the trick..

**Comment by neneone** [comment] 2023-09-30 17:28
> the issue is still there.. the fix mentioned above does the trick..

Same here, hopefully this gets fixed soon

**Closed as completed** 2023-12-04 12:42 UTC
Labels: bug, low priority
