### ISSUE TITLE
Notifications appearing below modal backdrop

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#5512] opened 2023-01-22 11:19 UTC
Even though notifications use `z-50` and modals use `z-40`, notifications appear below the modal backdrop.

This is probably because the "stacking context" is mixed up between these two elements? I'm not sure of the approach needed to fix this though.

You can reproduce the issue in the admin panel, using a `CreateAction` modal. When clicking "Create & create another", a notification should appear without the model closing.

**Comment by awcodes** [comment] 2023-01-23 00:04
The only way to do this is to pull the core notifications livewire component out of the topbar but that has issues with the db notifications trigger which is inside of that livewire component. And I'm not sure how best to split that out without loosing the context of the livewire component since the db trigger is using `$this`.

**Comment by danharrin** [comment] 2023-01-23 09:41
We could pass $this into the component as a prop?

**Comment by awcodes** [comment] 2023-01-23 12:22
`$this` is used in the view. So to pass in the livewire component would we have to create another component php class to have somewhere to pass it into?

**Comment by mwakalingajohn** [comment] 2023-03-25 18:51
I moved the @livewire('filament.core.notifications') out of the header element inside topbar.blade.php, it worked, and so far I am not seeing any issues

**Comment by awcodes** [comment] 2023-03-25 19:15
The problem is that it also renders the db notifications bell. So moving it out of the header breaks that.

**Comment by mwakalingajohn** [comment] 2023-03-25 21:49
Yeah, that moved the notification bell to the content area. I have found another workaround.

1. I have created a livewire component called trigger, and added the contents as follows:
`Livewire\Components\Notifications\Index.php`
```php
<?php

namespace App\Http\Livewire\Components\Notifications;

use Carbon\CarbonInterface;
use Filament\Notifications\Collection;
use Filament\Notifications\Notification;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Livewire\Component;


class Index extends Component
{

    public Collection $notifications;

    protected $listeners = [
        'notificationSent' => 'pushNotificationFromEvent',
        'notificationsSent' => 'pullNotificationsFromSession',
        'notificationClosed' => 'removeNotification',
    ];

    public function mount(): void
    {
        $this->notifications = new Collection();
        $this->pullNotificationsFromSession();
    }

    public function pullNotificationsFromSession(): void
    {
        foreach (session()->pull('filament.notifications') ?? [] as $notification) {
            $notification = Notification::fromArray($notification);

            $this->pushNotification($notification);
        }
    }

    public function pushNotificationFromEvent(array $notification): void
    {
        $notification = Notification::fromArray($notification);

        $this->pushNotification($notification);
    }

    public function removeNotification(string $id): void
    {
        if ($this->notifications->has($id)) {
            $this->notifications->forget($id);
        }

        if (! $this->hasDatabaseNotifications()) {
            return;
        }

        $this->getDatabaseNotificationsQuery()
            ->where('id', $id)
            ->delete();
    }

    public function clearDatabaseNotifications(): void
    {
        $this->getDatabaseNotificationsQuery()->delete();
    }

    public function markAllDatabaseNotificationsAsRead(): void
    {
        $this->getUnreadDatabaseNotificationsQuery()->update(['read_at' => now()]);
    }

    public function getDatabaseNotifications(): DatabaseNotificationCollection
    {
        /** @phpstan-ignore-next-line */
        return $this->getDatabaseNotificationsQuery()->get();
    }

    public function getDatabaseNotificationsQuery(): Builder | Relation
    {
        /** @phpstan-ignore-next-line */
        return $this->getUser()->notifications()->where('data->format', 'filament');
    }

    public function getUnreadDatabaseNotificationsQuery(): Builder | Relation
    {
        /** @phpstan-ignore-next-line */
        return $this->getDatabaseNotificationsQuery()->unread();
    }

    public function getUnreadDatabaseNotificationsCount(): int
    {
        return $this->getUnreadDatabaseNotificationsQuery()->count();
    }

    public function handleBroadcastNotification($notification): void
    {
        if (! is_array($notification)) {
            return;
        }

        if (($notification['format'] ?? null) !== 'filament') {
            return;
        }

        $this->pushNotification(Notification::fromArray($notification));
    }

    protected function pushNotification(Notification $notification): void
    {
        $this->notifications->put(
            $notification->getId(),
            $notification,
        );
    }

    public function hasDatabaseNotifications(): bool
    {
        return $this->getUser() && config('notifications.database.enabled');
    }

    public function getPollingInterval(): ?string
    {
        return config('notifications.database.polling_interval');
    }

    public function getDatabaseNotificationsTrigger(): ?View
    {
        $viewPath = config('notifications.database.trigger');

        if (blank($viewPath)) {
            return null;
        }

        return view($viewPath);
    }

    public function getUser(): Model | Authenticatable | null
    {
        return auth()->user();
    }

    public function getBroadcastChannel(): ?string
    {
        $user = $this->getUser();

        if (! $user) {
            return null;
        }

        if (method_exists($user, 'receivesBroadcastNotificationsOn')) {
            return $user->receivesBroadcastNotificationsOn();
        }

        $userClass = str_replace('\\', '.', $user::class);

        return "{$userClass}.{$user->getKey()}";
    }

    public function getNotificationFromDatabaseRecord(DatabaseNotification $notification): Notification
    {
        return Notification::fromDatabase($notification)
            ->date($this->formatNotificationDate($notification->getAttributeValue('created_at')));
    }

    protected function formatNotificationDate(CarbonInterface $date): string
    {
        return $date->diffForHumans();
    }

    public function render()
    {
        return view('livewire.components.notifications.index');
    }
}
```

`livewire.components.notifications.index.blade.php`
```blade
<div>
    <div @class([
        'filament-notifications pointer-events-none fixed inset-4 z-50 mx-auto flex justify-end gap-3',
        match (config('notifications.layout.alignment.horizontal')) {
            'left' => 'items-start',
            'center' => 'items-center',
            'right' => 'items-end',
        },
        match (config('notifications.layout.alignment.vertical')) {
            'top' => 'flex-col-reverse',
            'bottom' => 'flex-col',
        },
    ]) role="status">
        @foreach ($notifications as $notification)
            {{ $notification }}
        @endforeach
    </div>

    @if ($this->hasDatabaseNotifications())
        @php
            $notifications = $this->getDatabaseNotifications();
            $unreadNotificationsCount = $this->getUnreadDatabaseNotificationsCount();
        @endphp

        <div @if ($pollingInterval = $this->getPollingInterval()) wire:poll.{{ $pollingInterval }} @endif class="flex items-center">
            @if ($databaseNotificationsTrigger = $this->getDatabaseNotificationsTrigger())
                <x-notifications::database.trigger>
                    {{ $databaseNotificationsTrigger->with(['unreadNotificationsCount' => $unreadNotificationsCount]) }}
                </x-notifications::database.trigger>
            @endif

            <x-notifications::database.modal :notifications="$notifications" :unread-notifications-count="$unreadNotificationsCount" />
        </div>
    @endif

    @if ($broadcastChannel = $this->getBroadcastChannel())
        <x-notifications::echo :channel="$broadcastChannel" />
    @endif
</div>
```
2. I created another livewire component called trigger as follows:
`Livewire\Components\Notifications\Trigger.php`
```php
<?php

namespace App\Http\Livewire\Components\Notifications;

use Carbon\CarbonInterface;
use Filament\Notifications\Collection;
use Filament\Notifications\Notification;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Livewire\Component;

class Trigger extends Component
{

    public function getUser(): Model | Authenticatable | null
    {
        return auth()->user();
    }


    public function getDatabaseNotificationsQuery(): Builder | Relation
    {
        /** @phpstan-ignore-next-line */
        return $this->getUser()->notifications()->where('data->format', 'filament');
    }

    public function getUnreadDatabaseNotificationsQuery(): Builder | Relation
    {
        /** @phpstan-ignore-next-line */
        return $this->getDatabaseNotificationsQuery()->unread();
    }

    public function getUnreadDatabaseNotificationsCount(): int
    {
        return $this->getUnreadDatabaseNotificationsQuery()->count();
    }

    public function render()
    {
        return view('livewire.components.notifications.trigger');
    }
}
```
`livewire.components.notifications.trigger.blade.php`
```blade
@php
    $unreadNotificationsCount = $this->getUnreadDatabaseNotificationsCount();
@endphp

<div x-data="{}" x-on:click="$dispatch('open-modal', { id: 'database-notifications' })" class="inline-block">
    <button title="Open notifications" type="button"
        class="filament-icon-button flex items-center justify-center rounded-full relative outline-none hover:bg-gray-500/5 disabled:opacity-70 disabled:cursor-not-allowed disabled:pointer-events-none text-primary-500 focus:bg-primary-500/10 dark:hover:bg-gray-300/5 w-10 h-10 ml-4 -mr-1 rtl:-ml-1 rtl:mr-4">
        <span class="sr-only">
            Open notifications
        </span>

        <svg wire:loading.remove.delay="" wire:target="" class="filament-icon-button-icon w-5 h-5"
            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
            aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round"
                d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9">
            </path>
        </svg>

        <span
            class="filament-icon-button-indicator absolute rounded-full text-xs inline-block w-4 h-4 -top-0.5 -right-0.5 bg-primary-500/10">
            {{$unreadNotificationsCount}}
        </span>
    </button>
</div>
```

3. Finally I modified the `topbar.blade.php` as follows
```blade
@props([
    'breadcrumbs' => [],
])

<header
    {{ $attributes->class([
        'filament-main-topbar sticky top-0 z-10 flex h-16 w-full shrink-0 items-center border-b bg-white',
        'dark:bg-gray-800 dark:border-gray-700' => config('filament.dark_mode'),
    ]) }}>
    <div class="flex items-center w-full px-2 sm:px-4 md:px-6 lg:px-8">
        <button x-cloak x-data="{}"
            x-bind:aria-label="$store.sidebar.isOpen ? '{{ __('filament::layout.buttons.sidebar.collapse.label') }}' :
                '{{ __('filament::layout.buttons.sidebar.expand.label') }}'"
            x-on:click="$store.sidebar.isOpen ? $store.sidebar.close() : $store.sidebar.open()"
            @class([
                'filament-sidebar-open-button shrink-0 flex items-center justify-center w-10 h-10 text-primary-500 rounded-full outline-none hover:bg-gray-500/5 focus:bg-primary-500/10',
                'lg:mr-4 rtl:lg:mr-0 rtl:lg:ml-4' => config(
                    'filament.layout.sidebar.is_collapsible_on_desktop'),
                'lg:hidden' => !(
                    config('filament.layout.sidebar.is_collapsible_on_desktop') &&
                    config('filament.layout.sidebar.collapsed_width') === 0
                ),
            ])>
            <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
        </button>

        <div class="flex items-center justify-between flex-1">
            <x-filament::layouts.app.topbar.breadcrumbs :breadcrumbs="$breadcrumbs" />

            @livewire('filament.core.global-search')

            @livewire("components.notifications.trigger")

            <x-filament::layouts.app.topbar.user-menu />
        </div>
    </div>
</header>
@livewire('components.notifications.index')
```

**Comment by zepfietje** [comment] 2023-04-26 07:15
This issue has been fixed now. 👌
Reference: https://github.com/filamentphp/filament/commit/1dafe346d5c69b95fe13881d0dcfc43c8997af48.

**Closed as completed by zepfietje** 2023-04-26 07:15 UTC
Labels: bug, ui
