### ISSUE TITLE
Delay Response and Sometimes Table Action Buttons like View always open on second click not on first click

### ISSUE THREAD

**Issue by webdevsamran** [laravel-filament/filament#12139] opened 2024-04-02 06:49 UTC
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11.0

### PHP Version

8.2

### Problem description

I'm building an Employee Management System having more than 30 CRUD Operations right now. The problem is Table Action Buttons gives a delay response not instant and also some time I use **Infolist** and then when I pressed on **View** Button present on the Table row, it doesn't take my first click and I always have to second click to open the **infolist**. Also there is Delay here which I want is instant

### Expected behavior

I want to have Instant Response to my actions and also make sure to open **infolist** on every click not second click of each time.

### Steps to reproduce

The steps are simple. Install the filament. I have already made three resources. you just need to tell why there is slow response on Action buttons and also why I always need to click twice for opening of infolist.

### Reproduction repository

https://github.com/webdevsamran/ems_test

**Comment by dmitry-udod** [comment] 2024-04-22 08:32
@webdevsamran Hi! Could you check and update your reproduction repository because there are a lot of missing models? For example: CvSkill, CvType, CvSource, CvMedium, Department, Designation, LeaveCategory, PaySlip, PayHead, etc.
That's why I can't run migrate & seed to reproduce the issue.

**Comment by krzysztofengineer** [comment] 2024-05-03 12:35
i have the same issue. Table header action always open on second click

**Comment by dmitry-udod** [comment] 2024-05-03 13:24
@krzysztofengineer Hi! Could you please provide a valid reproduction repository?

**Comment by webdevsamran** [comment] 2024-05-03 13:42
Thanks all for replying 
The issue is resolved 
I resolved it by enabling OP cache and making cache of icons, components and route
Then this issue is resolved

**Comment by dmitry-udod** [comment] 2024-05-03 18:05
@webdevsamran hi! If everything is ok, could you close the issue, please

**Closed as completed** 2024-05-04 09:33 UTC
Labels: bug, unconfirmed, low priority
