### ISSUE TITLE
Repeater bug when have searchable select field inside

### ISSUE THREAD

**Issue by margarizaldi** [laravel-filament/filament#7940] opened 2023-08-21 05:54 UTC
### Package

filament/filament

### Package Version

v3.0.27

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta10

### PHP Version

PHP 8.1.10

### This bug only happens when we have searchable select input inside the repeater.

When deleting or moving an item, the item looks deleted but the console says:
`select.js?v=3.0.27.0:1 Uncaught (in promise) Could not find Livewire component in DOM tree`
or
`select.js?v=3.0.27.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clearStore')`
or 
`select.js?v=3.0.27.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clear')`
and/or with warning:
`Trying to initialise Choices on element already initialised`

Then when adding an item after that, it will create 2 items (or more in further situations).

### Expected behavior

The row must be deleted and without bringing issue after that.

### Steps to reproduce

- Clone the repo, configure, install, etc. User seeder is available: `test@example.com`, pass: `password`
- Go to `Foos` create page
- Play around with the Select items (add, delete or move)
- You'll see the glitches, and 
- Check the console

### Reproduction repository

https://github.com/margarizaldi/filament-repeater-bug

### Relevant log output

```shell
select.js?v=3.0.27.0:1 Uncaught (in promise) Could not find Livewire component in DOM tree

select.js?v=3.0.27.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clearStore')

select.js?v=3.0.27.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clear')
```

**Comment by zepfietje** [comment] 2023-08-21 08:49
@margarizaldi could you provide the exact version of Livewire you're using and test on the latest beta?

**Comment by mustafa-online** [comment] 2023-08-21 12:46
I'm facing the exact issue.
--
**PHP**: 8.2
**Laravel**: 10.19
**Livewire**: v3.0.0-beta.10
**Filament**: v3.0.30

**Comment by Cannonb4ll** [comment] 2023-08-21 17:13
I have the same issue, and reported this earlier as well, including a reproduction repository: https://github.com/filamentphp/filament/issues/7584

Others, have reported this as well; https://github.com/filamentphp/filament/issues/7485

I'm on the latest Livewire, latest Laravel & Filament versions:

Laravel: 10.19
Livewire: v3.0.0-beta.10
Filament: v3.0.30

Given though, just add the following code in a random project you have that runs Filament V3 basically, you'd get the repeater bug (video inside my issue):

```php
return $form
    ->schema([
        Forms\Components\Repeater::make('test')->columns(2)->schema([
            Forms\Components\TextInput::make('hi'),
            Forms\Components\Select::make('options')
                ->searchable()
                ->options([
                    'one', 'two'
                ])
        ]),
    ]);
```

Good thing to know, this **only** happens if there's JS introduced inside the form component, in this case, AlpineJS because of the searchable select field. If you remove the `->searchable()`, all is fine.

**Comment by pochocho** [comment] 2023-08-21 22:15
Having the same issue, I reported it here  #7893 and linked to the demo site repository since you can also see the bug there on the orders page when using the repeater. I also confirmed now that it does go away if you use the native select (no js on it)

**Comment by margarizaldi** [comment] 2023-08-22 13:32
> @margarizaldi could you provide the exact version of Livewire you're using and test on the latest beta?

@zepfietje I've updated this post, the reproduction repo is using the latest livewire 3 beta 10.

**Comment by lucas-pace** [comment] 2023-08-24 06:07
I'm facing the exact issue too

PHP: 8.2
Laravel: 10.19
Livewire: v3.0.0-beta.9
Filament: v3.0.27

**Comment by danharrin** [comment] 2023-08-25 17:53
I believe livewire/livewire#6521 is a failing test for this

**Comment by pullaf** [comment] 2023-08-31 11:46
Getting this error even without a repeater, just 3 searchable relationship selects in a modal (and I get it 3 times as soon as I close the modal)

**Comment by naveen-murali-av** [comment] 2023-09-05 12:20
I am also getting this issue, 

PHP: 8.1
Laravel: 10.21.1
Livewire: v3.0.1
Filament: v3.0.39

**Comment by danharrin** [comment] 2023-09-05 15:20
Yup, that fix hasnt been released by Livewire yet.

**Comment by danharrin** [comment] 2023-09-07 06:47
Should be fixed by livewire/livewire#6521

**Comment by Cannonb4ll** [comment] 2023-09-07 06:48
Can confirm it's working as expected.

**Closed as completed by danharrin** 2023-09-07 06:47 UTC
Labels: bug, unconfirmed

**Comment by larasmartCom** [comment] 2023-10-03 15:39
I'm facing the exact issue too

PHP: 8.2
Laravel: 10.26.2
Livewire: v3.0.5
Filament: v3.0.63

console
```javascript
Uncaught (in promise) TypeError: this.select is null
 http://localhost:8000/js/filament/forms/components/select.js?v=3.0.63.0:1
```

If you remove the ->searchable(), all is fine.

**Comment by danielbehrendt** [comment] 2023-12-09 16:06
Using a `Select` field with `->multiple(function (Get $get, $livewire) {....}` in a `Repeater` seems also to cause this error after saving.
