### ISSUE TITLE
Problem with modals and QueryBuilder

### ISSUE THREAD

**Issue by piotrh052b** [laravel-filament/filament#13666] opened 2024-07-23 07:02 UTC
### Package

filament/filament

### Package Version

v 3.2.95

### Laravel Version

v 11.16.0

### PHP Version

PHP 8.2.11

### Problem description

When QueryBuilder with constraints are added to resource then modall windows and column sorting stop working. 

### Expected behavior

Modals and sorting should still work.

### Steps to reproduce

1. Blog -> Posts.
2. Clik on Add rule
3. Pick Author or Blog author id and select any author
4. Click on Delete action and then Cancel button in modal (or close ith with x button)
5. Again click on Delete action - is no longer working

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/052b/filament-demo/tree/main

### Relevant log output

```shell
[2024-07-23 08:44:03] local.ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4194312 bytes) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 536870912 bytes exhausted (tried to allocate 4194312 bytes) at D:\\laragon\\www\\filament-demo\\vendor\\livewire\\livewire\\src\\Features\\SupportValidation\\HandlesValidation.php:490)
```

**Comment by Montaserz** [comment] 2024-07-23 07:50
It looks like an issue related to your server, try increasing memory_limit in your php.ini

**Comment by danharrin** [comment] 2024-12-11 10:22
Duplicate of #12554

**Closed as not planned by danharrin** 2024-12-11 10:22 UTC
Labels: bug, unconfirmed, medium priority
