### ISSUE TITLE
RepeatableEntry model injection

### ISSUE THREAD

**Issue by prazny** [laravel-filament/filament#8923] opened 2023-10-06 11:48 UTC
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

v10.26.2

### Livewire Version

v3.0.5

### PHP Version

PHP 8.1

### Problem description

Making RepeatableEntry with Actions is what I'm attempting. I have a model called "Order" that has many "Offers."  "Order" models are used in the action functions.

```
return $infolist
            ->schema([
                Infolists\Components\TextEntry::make('name')->label(__("name")),
                Infolists\Components\RepeatableEntry::make('offers')
                    ->schema([
                        Infolists\Components\TextEntry::make('content')->label(__("content")),
                        Infolists\Components\Actions::make([
                            Actions\Action::make("test")
                                ->url(function (Model $model) {
                                    return "example.com/" . $model->id; // expected Offer but Order is returned
                                })
                        ]),
                    ])
            ]);
```

### Expected behavior

I have expected to have Offer in action function url()/action();

### Steps to reproduce

1. Make two models that are related many to one.
2. Create a RepeatableEntry with a variety of offers.
3. Implement action in RepeatableEntry.

### Reproduction repository

https://github.com/prazny/repeatable-reproduction

**Comment by zepfietje** [comment] 2023-10-06 15:08
Duplicate of https://github.com/filamentphp/filament/issues/6964?

**Comment by prazny** [comment] 2023-10-06 19:16
> Duplicate of #6964?

Not sure. If i add code metioned in #6964 I have the same problem but proposed correction by  @fallback solves it while my problem still persists.

**Comment by zepfietje** [comment] 2023-10-07 07:00
Alright, thanks for checking.
It's probably a different bug report I've seen before, or maybe I encountered it myself sometime.
Will keep this issue open.

**Comment by awcodes** [comment] 2023-10-13 17:22
hey @prazny 

this will solve your issue:

```php
Infolists\Components\Actions::make([
  Actions\Action::make("test")
      ->url(function (Model $record, Actions\Action $action) {
          $data = $action
              ->getInfolistComponent()
              ->getContainer()
              ->getParentComponent()
              ->getState();
  
          return "https://example.com/" . $data['id'];
      })
 ])
```

@danharrin we could potentially add this as a check on the infolist action with a fallback to the the non repeatable $record, but I don't know if it would be better as a different parameter to inject since using `$record` might be confusing since the contexts aren't really discernible from the code.

Could potentially be an issue with the `Actions` container too, since similar behavior being reported with form repeaters involving actions.

**Comment by danharrin** [comment] 2023-12-07 01:22
it works just fine if you swap `Model $model` or `Model $record` using the original code example, I didn't even need the suggestion from Adam

Maybe a recent update thing

**Closed as not planned by danharrin** 2023-12-07 01:22 UTC
Labels: bug, confirmed, low priority

**Comment by rhino-corey** [comment] 2025-10-08 16:04
Is there really no plans for this? It's still an issue in v4. The use case is definitely there.

Adding an action into a RepeatableEntry schema and allowing the entry's record to be injected would be very useful. Injecting the parent record into an action within a RepeatableEntry is not that useful. Opening a modal or executing a task for the individual entry record is what we're trying to achieve.

**Comment by danharrin** [comment] 2025-10-08 16:09
@rhino-corey open an issue with a v4 reproduction repository if this has reoccured
