### ISSUE TITLE
unable to select per page in table when seeded a lot of data

### ISSUE THREAD

**Issue by gyaanesh** [laravel-filament/filament#8890] opened 2023-10-04 18:03 UTC
### Package

filament/filament

### Package Version

^3.0

### Laravel Version

10.26.2

### PHP Version

8.1

### Problem description

I created some tables in filament admin to display my data. when the number of total pages is less  I cansee and change per page record as in this screenshot
![image](https://github.com/filamentphp/filament/assets/43063785/c294410b-2e41-4843-8e93-81021395d196)

but then I seeded 30,000 records to my table now I  am not able to select the per page because the page links are coming on top of the per page section. The screenshot is given below.
![image](https://github.com/filamentphp/filament/assets/43063785/a5d4d9ff-c1a0-4b13-b376-e37000a60263)

and when changing the current active page I cant even see per page section 
![image](https://github.com/filamentphp/filament/assets/43063785/38a3c284-3dff-4b16-9874-4badd76c5b43)

### Expected behavior

page links should not overflow

### Steps to reproduce

seeded 30k rows working fine for less data
PHP artisan db:seed --class=CompanySeeder

### Reproduction repository

https://github.com/gyaanesh/filament.git

**Comment by awcodes** [comment] 2023-10-04 18:56
Duplicate of #7597

**Comment by zepfietje** [comment] 2023-10-05 07:45
Closing as dupe.

**Closed as not planned by zepfietje** 2023-10-05 07:45 UTC
Labels: bug, duplicate, low priority

**Comment by gyaanesh** [comment] 2023-10-05 07:46
how can i resolve it ??

**Comment by zepfietje** [comment] 2023-10-05 08:05
Please read the discussion on https://github.com/filamentphp/filament/issues/7597 and let us know if you want to attempt a fix. 🙂

**Comment by gyaanesh** [comment] 2023-10-05 15:12
> Please read the discussion on #7597 and let us know if you want to attempt a fix. 🙂

Hi i just Updated Your Core Files And Now Its better for me 
![image](https://github.com/filamentphp/filament/assets/43063785/37f210a6-2936-47b1-b410-ae39647a1cba)

edited file Views->vendor->filament->component->pagination->index.blade.php

Removed code
 ```
            @foreach ($paginator->render()->offsetGet('elements') as $element)
                @if (is_string($element))
                    <x-filament::pagination.item disabled :label="$element" />
                @endif

                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        <x-filament::pagination.item
                            :active="$page === $paginator->currentPage()"
                            :aria-label="trans_choice('filament::components/pagination.actions.go_to_page.label', $page, ['page' => $page])"
                            :label="$page"
                            :wire:click="'gotoPage(' . $page . ', \'' . $paginator->getPageName() . '\')'"
                            :wire:key="$this->getId() . '.pagination.' . $paginator->getPageName() . '.' . $page"
                        />
                    @endforeach
                @endif
            @endforeach

```

**Replaced With** 

```
@php
                $maxPageLinks = 2; // Include 2 pages before and after the current page, as well as the first and last pages.
            @endphp
            @foreach ($paginator->render()->offsetGet('elements') as $element)
                @if (is_string($element))
                    <x-filament::pagination.item disabled :label="$element" />
                @endif

                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if (
                            ($page <= $paginator->currentPage() + $maxPageLinks && $page >= $paginator->currentPage() - $maxPageLinks) ||
                                // Include the first page
                                $page === 1 ||
                                // Include the last page
                                $page === $paginator->lastPage())
                            <x-filament::pagination.item :active="$page === $paginator->currentPage()" :aria-label="trans_choice('filament::components/pagination.actions.go_to_page.label', $page, [
                                'page' => $page,
                            ])" :label="$page"
                                :wire:click="'gotoPage(' . $page . ', \'' . $paginator->getPageName() . '\')'"
                                :wire:key="$this->getId() . '.pagination.' . $paginator->getPageName() . '.' . $page" />
                        @endif
                    @endforeach
                @endif
            @endforeach
```

**Comment by zepfietje** [comment] 2023-10-05 15:22
Please read the discussion I linked to, as this isn't the ideal solution.
