### ISSUE TITLE
Builder broken - Undefined array key "type"

### ISSUE THREAD

**Issue by martin-ro** [laravel-filament/filament#7450] opened 2023-08-04 10:45 UTC
### Package

filament/filament

### Package Version

v3.0.7

### Laravel Version

v10.17.1

### PHP Version

PHP 8.2

### Problem description

Simple Builder setup causes error `Undefined array key "type"` when saving/deleting.

Error: https://flareapp.io/share/87ne66yP

### Expected behavior

Adding and removing blocks without error.

### Steps to reproduce

1. Add to resource form:
```php
Forms\Components\Builder::make('builder')
                    ->blocks([
                        Forms\Components\Builder\Block::make('block')
                            ->schema([
                                Forms\Components\Toggle::make('enabled'),
                                Forms\Components\TextInput::make('title'),
                            ]),
                    ])
```

2. Add Block
3. Remove Block
4. Add Block
5. Remove Block --> Error `Undefined array key "type"`

### Reproduction repository

https://github.com/martin-ro/f3

### Relevant log output

```shell
https://flareapp.io/share/87ne66yP
```

**Comment by pboivin** [comment] 2023-08-04 14:44
I'm also running into the same issue. I've been pulling my hair out silently trying to determine if the issue is on my end! I'll see if I can reproduce with your provided repository.

Edit: Yes, I could reproduce the issue!

**Comment by pboivin** [comment] 2023-08-06 15:49
I'm digging into this a bit and I suspect it could be a bug in Livewire. Here's a breakdown of the `update` requests that happen in the Network tab of my dev tools when I'm following the steps described in the issue description:

![1](https://github.com/filamentphp/filament/assets/7805679/10da5bce-41fd-4782-a19e-649755f5c53d)

**Comment by martin-ro** [comment] 2023-08-06 20:16
yes, I saw exactly the same thing.

**Comment by danharrin** [comment] 2023-08-09 15:22
Just to let you know we are looking into this. I believe that #7421, #7450, #7475 and #7485 (and other duplicate issues) are all the same bug, related to Livewire's entangle feature.

**Comment by danharrin** [comment] 2023-08-09 15:35
livewire/livewire#6289

**Comment by amondar-libs** [comment] 2023-08-22 15:13
Still not worked on liveware 3.0.0-beta10. Same error: Undefined array key "type", but looks like fix already merged

**Comment by danharrin** [comment] 2023-08-25 17:52
I believe livewire/livewire#6521 is a failing test for this

**Comment by mrahmadt** [comment] 2023-09-11 06:50
I'm getting this error from just creating the example at https://filamentphp.com/docs/3.x/forms/fields/builder

any suggested workaround?

**Comment by danharrin** [comment] 2023-09-11 07:33
Upgrade Livewire and Filament

**Comment by martin-ro** [comment] 2023-12-07 06:42
I'm still experiencing this bug on v3.1.14

**Comment by RobertsG** [comment] 2023-12-07 13:58
Also encountering this on with Filament v3.1.14 and livewire v3.2.6.

**Comment by danharrin** [comment] 2023-12-12 18:52
Should be fixed in the next release. 5e58bea68018a02a904d9377a3a3baa0b08956a8

**Closed as completed by danharrin** 2023-12-12 18:52 UTC
Labels: bug, confirmed, high priority

**Comment by dinandmentink** [comment] 2024-01-19 17:17
Is there a fix/workaround for this in filament v2.0? I'm running the newest version.

**Comment by danharrin** [comment] 2024-01-19 18:30
Feel free to submit a PR and I will merge/release it.
