### ISSUE TITLE
TextEntry on Infolists forces 3 columns when inlineLabel is enabled

### ISSUE THREAD

**Issue by RixzZ** [laravel-filament/filament#10983] opened 2024-01-22 07:54 UTC
### Package

filament/infolists

### Package Version

v3.1.47

### Laravel Version

v10.41.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.3.0

### Problem description

When using TextEntry on Infolists, if you enable inlineLabel, you end up with a 3 column grid:

- 1: The label.
- 2+3 (with colspan): The value.

This creates a kind of right margin (corresponding to the 3rd column) next to inlineLabel entries, which it's visually unpleasing when you have a slim section (not full width) to display the data.

### Expected behavior

Unless there is a 3rd piece of data the shows on the 3rd column, you should have two columns (or have a way to configure it), one for the label and one for the data.

I guess it can be intentional, to have a 33%+66% ratio of label+data, but if you data is short, it doesn't end up well.

### Steps to reproduce

I added two entries in the code example, one with inlineLabel and the other without it.

Also forced some borders, where you can see the disposition. There are 3 columns and the 2 and 3 are colspanned.

Screenshot for clarity:
<img width="1295" alt="SCR-20240122-idki" src="https://github.com/filamentphp/filament/assets/1339272/4cf11b00-1581-4a80-93dd-5a38202d5f87">

### Reproduction repository

https://github.com/RixzZ/filament-issue-02

**Comment by zepfietje** [comment] 2024-01-22 09:53
This is by design.
Inline infolist entries or form fields use a 3 column grid, where the label takes up 1 cell and the actual content the other 2 cells.

I don't really understand what's the issue here, so feel free to clarify or attempt a PR if you think this is something that should and can be fixed in a non-breaking way.

Thanks!

**Closed as not planned by zepfietje** 2024-01-22 09:53 UTC
Labels: bug, unconfirmed, low priority

**Comment by goyote** [comment] 2024-10-28 09:28
Fix:

`.fi-in-entry-wrp > div {
    @apply sm:grid-cols-2;
}

.fi-in-entry-wrp > div > :last-child {
    @apply sm:col-span-1;
}
`
