### ISSUE TITLE
Nested relationships not working on creation.

### ISSUE THREAD

**Issue by danielbehrendt** [laravel-filament/filament#6039] opened 2023-03-27 14:20 UTC
### Package

filament/filament

### Package Version

v2.17.18

### Laravel Version

v10.4.1

### PHP Version

PHP 8.2.4

### Problem description

When trying to `create` a new model with 2 level nested relations only the first level gets saved.

The nested structure is as followed:

-> user
--> person
---> contact

All these relations are defined by `morphOne` relationships. 

### Expected behavior

After saving the new model only `user` and `person` exist but the expected behavior would be the have a `user` with a `person` and a `contact` belonging to the `person`.

In case of `edit` it works but not in case of `create`.

### Steps to reproduce

Download "Reproduction repository" and run

```
composer install
```

Edit .env file and the run

```
php artisan migrate
php artisan make:filament-resource User
```

Login in to Filament admin and try to create e new user.

### Reproduction repository

https://github.com/danielbehrendt/filament-test

**Comment by danharrin** [comment] 2023-04-01 17:55
Fixed by #6092.

**Comment by zepfietje** [comment] 2023-04-11 07:57
Has this issue been reopened on purpose, @danharrin?

**Comment by danharrin** [comment] 2023-04-11 08:00
Yes apparently it didnt fix

**Comment by danharrin** [comment] 2023-04-30 16:25
I just downloaded the same repository again, I was pretty sure the issue was fixed last time I closed it but this was reported.

I see no issues with the behaviour. I have attached a screen recording.

https://user-images.githubusercontent.com/41773797/235364316-8904a9f2-c0fd-4e8e-a3a1-8a6cd95b95b8.mov

@danielbehrendt please double check you're on the latest Filament version. Make sure no versions are locked in your composer.json. Run `artisan about` to check the Filament version. If the issue persists, please create another reproduction in a fresh Laravel project because this one is not helping me.

**Closed as completed by danharrin** 2023-04-30 16:25 UTC
Labels: bug, unconfirmed

**Comment by danharrin** [comment] 2023-04-30 16:35
Btw - I tested it with the latest 2.x branch. Potentially #6363 fixed the problem. So it's worth updating to the latest version of Filament before testing, it could be that 👍

**Comment by JonatasBSM** [comment] 2024-08-11 14:21
It should work at filament 3? Im having the same problem with belongsTo nested relations

**Comment by mangtri99** [comment] 2024-08-15 09:23
This issue still happen on version 3

**Comment by danharrin** [comment] 2024-08-15 09:33
We investigate open issues with reproduction repositories, if you open one we will look at it

**Comment by JonatasBSM** [comment] 2024-12-12 15:43
> We investigate open issues with reproduction repositories, if you open one we will look at it

I just created one: https://github.com/JonatasBSM/nestedbelongstotest

adress belongs to city and city belongs to state

on address form you have "City's name" and "State's name" to create both city and state. when you create address record, city will also be created, but the state won't

**Comment by stian-scholtz-snappi** [comment] 2025-08-19 08:20
Hi @danharrin. Can you please confirm whether or not this is supposed to work? I was unable to this on v3 and v4.

For example, I have an OrderResource. The form creates an Order, the form includes a Fieldset for the delivery_address relation (belongsTo), and the delivery_address has a contact relation(belongsTo). So Order -> DeliveryAddress -> Contact. As soon as you go 3+ levels deep with relations the form will throw validation errors, be unable to save if you manually adjust validation using mutateStateForValidationUsing, etc.

**Comment by danharrin** [comment] 2025-08-19 09:08
@stian-scholtz-snappi it's not entirely clear, can you open an issue with a reproduction repository please?

**Comment by stian-scholtz-snappi** [comment] 2025-08-19 11:02
@danharrin I made a simple repo:

https://github.com/stian-scholtz-snappi/filament_nested_relation_demo
 
You will see the error when submitting the form.

**Comment by danharrin** [comment] 2025-08-19 11:03
Please open an issue describing it, this issue is closed

**Comment by stian-scholtz-snappi** [comment] 2025-08-19 12:12
Apologies, I've create an issue: https://github.com/filamentphp/filament/issues/17407
