### ISSUE TITLE
DirectoryIndex error with custom assets path

### ISSUE THREAD

**Issue by capetrel** [laravel-filament/filament#11051] opened 2024-01-25 10:04 UTC
### Package

filament/filament

### Package Version

3.2

### Laravel Version

10.10

### Livewire Version

3

### PHP Version

8.2

### Problem description

Get a 403, Fobiden error when visiting /admin route

### Expected behavior

Redirect to login or get dashboard panel

### Steps to reproduce

create a new laravel project and install filament : 
`composer require filament/filament`
`php artisan filament:install --panels` (keep default name 'admin')

Launch migration `php artisan migrate`

- create user : `php artisan make:filament-user`
- publish configuration file : `php artisan vendor:publish --tag=filament-config`
- change the assets_path : replace null by 'admin'

create an 'admin' folder in public directory, cut and past css and js filament's folder in it.

go to : you-url/admin for an 403 Forbidden error.
Check apache error.log to see : 
`autoindex:error] [pid 16416:tid 1924] [client 127.0.0.1:53193] AH01276: Cannot serve directory D:/web/www/bug-filament/public/admin/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive`

It's on a local environment, maybe it can be a bad apache configuration, but i spend some time to find it because of the '403 error in production mode' 

### Reproduction repository

https://github.com/capetrel/test-filament.git

**Comment by danharrin** [comment] 2024-01-26 10:05
Sorry, but I am definitely going to close this as I'm quite sure it is not a bug, probably a setup issue. Please use our Discord or GitHub Discussions for diagnosis help.

**Closed as not planned by danharrin** 2024-01-26 10:05 UTC
Labels: bug, unconfirmed, low priority
