### ISSUE TITLE
Modal is opening on Livewire valdiation

### ISSUE THREAD

**Issue by alexmanase** [laravel-filament/filament#8522] opened 2023-09-15 13:11 UTC
### Package

filament/filament

### Package Version

v3.0.50

### Laravel Version

v10.23.1

### Livewire Version

v3.0.4

### PHP Version

PHP 8.2.2

### Problem description

When I press a button, in order to trigger an action from the inside of a Filament form, a blank modal is opening.

https://github.com/filamentphp/filament/assets/10696975/affe8294-013b-43af-b362-fe590db703fb

### Expected behavior

Perform the action from the callback without opening a modal.

### Steps to reproduce

1. Clone https://github.com/alexmanase/filament-modal-on-submit-issue
2. Follow the instruction from `README.md` in order to install
3. Press the 'Edit' button
4. Press 'Generate' button, with the "keywords" field empty
5. Fill the "keywords" field
6. Press 'Generate' button

### Reproduction repository

https://github.com/alexmanase/filament-modal-on-submit-issue

**Comment by danharrin** [comment] 2023-09-15 16:18
404 on that reproduction repo

**Comment by alexmanase** [comment] 2023-09-15 16:35
Sorry, I made it by private by mistake. It's public now.

**Comment by zepfietje** [comment] 2023-09-25 13:34
Duplicate of https://github.com/filamentphp/filament/issues/7909.

**Closed as not planned by zepfietje** 2023-09-25 13:34 UTC
Labels: bug, unconfirmed, low priority
