### ISSUE TITLE
Browse button doesn't work when removing a file

### ISSUE THREAD

**Issue by zltn** [laravel-filament/filament#278] opened 2021-03-23 17:18 UTC
**Describe the bug**
Browse button doesn't work when removing an image

**To reproduce**
1. Create a fileupload component 
2. Upload a file and save
3. Reload the page (if you remove it right away the browse button does work)
4. Remove the file
5. Click browse, nothing happens. If you drag and drop a file it does upload it

**Expected behavior**
Browse window should open

**Screenshots**

**Context**
- Package version: Latest
- Browser: Safari

**Comment by danharrin** [comment] 2021-03-25 12:40
I can't replicate this? Can you update to the latest version and recheck, or provide a repo.

**Comment by danharrin** [comment] 2021-04-11 19:28
Hey, gonna close this issue as I am unable to reproduce the issue. If it's still present in the latest version, please let me know and I'll reopen this. Thanks!

**Closed by danharrin** 2021-04-11 19:28 UTC
Labels: bug, cannot reproduce
