### ISSUE TITLE
grid layout in Cluster to much space between widgets and/or content (with FIX / SOLUTION)

### ISSUE THREAD

**Issue by eelco2k** [laravel-filament/filament#13037] opened 2024-05-31 14:48 UTC
### Package

filament/filament

### Package Version

v3.2.85

### Laravel Version

v10.48.12

### Livewire Version

v3.5.0

### PHP Version

8.3.7

### Problem description

When using a Cluster with a lot of menu items. all pages and resources who have header Widgets have too much space between the header Widgets and the content below (tables).

### Expected behavior

There should be not much space between widgets and content.

### Steps to reproduce

After installing repo. Go to the Life Cluster page, then to the Users Page. space between widgets and table is growing when there are more navigation items in the menu. it also gets worse if you add more users to the usersResource table...

 you can also resize the window to see the whitespace growing or shrinking...

vendor/filament/filament/resources/views/components/page/index.blade.php and starting on line 57:

```php
@class([
                'flex flex-col gap-8' => $subNavigation,
                match ($subNavigationPosition) {
                    SubNavigationPosition::Start, 
                    SubNavigationPosition::End => 'md:flex-row',
                    default => null,
                } => $subNavigation,
                'h-full' => $fullHeight,
            ])
        >
```

should have and extra class `md:items-start` behind `md:flex-row`:

like so:
```php
@class([
                'flex flex-col gap-8' => $subNavigation,
                match ($subNavigationPosition) {
                    SubNavigationPosition::Start, 
                    SubNavigationPosition::End => 'md:flex-row md:items-start',
                    default => null,
                } => $subNavigation,
                'h-full' => $fullHeight,
            ])
        >
```

### Reproduction repository

[https://github.com/eelco2k/filamentphp-issue-cluster](https://github.com/eelco2k/filamentphp-issue-cluster)

**Comment by zepfietje** [comment] 2024-06-01 06:58
Duplicate of #11909.

**Closed as not planned** 2024-06-01 06:58 UTC
Labels: bug, unconfirmed, medium priority
