### ISSUE TITLE
Wizard Modal created using the `steps` method of an Action is not usable currently.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-filament/filament#7177] opened 2023-07-24 08:52 UTC
### Package

filament/filament

### Package Version

v3.0.0-beta7

### Laravel Version

v10.10

### Livewire Version

v3.0-beta.3

### PHP Version

PHP 8.2

### Problem description

When using a wizard as a modal form for an Action, if one of the `Select` fields has the `createOptionForm` to create a new item on the dropdown, on clicking the `+` button, the modal to create new records does not show. This is not the case when the action uses a modal form and only happens when the `steps()` function is used to create wizard steps for the action.

Console Error:
<img width="664" alt="CleanShot 2023-07-24 at 14 25 00@2x" src="https://github.com/filamentphp/filament/assets/1639302/f7f89c0d-f010-4520-be87-1d04c63c67c5">

### Expected behavior

The `createOptionForm` should show the modal to create the modal window irrespective of if the wizard steps or the form is used.

### Steps to reproduce

1.  run `php artisan migrate`
2. Visit `/`

```php
Action::make('create')
                ->label('New Job Listing')
                ->extraAttributes([
                    'class' => 'bg-gradient-purple-left'
                ])
                ->steps([
                    Wizard\Step::make('Location')
                        ->schema([
                            TextInput::make('name'),
                            TextInput::make('email'),
                            Select::make('company_location_id')
                                ->relationship('location', 'id')
                                ->label('Location')->required()
                                ->createOptionForm([
                                    Select::make('country_id')
                                        ->label('Country')
                                        ->required(),

                                    Select::make('state_id')
                                        ->label('State')
                                        ->required(),
                                ])
                                ->columnSpan(2)
                                ->helperText('Select the location where the job is based')
                        ])
                ])
```

### Reproduction repository

https://github.com/abishekrsrikaanth/filament-test

**Comment by zepfietje** [comment] 2023-07-24 08:53
Could you provide any console errors?

**Comment by zepfietje** [comment] 2023-07-24 08:54
Also make sure to provide a minimal reproduction repository we can access. Without it, it's hard for us to look into the issue. Let us know once you've added it, then we'll reopen this issue.

**Comment by abishekrsrikaanth** [comment] 2023-07-24 09:10
@zepfietje Added the code to the repository and the console error

**Comment by zepfietje** [comment] 2023-07-24 09:17
Thanks.

**Comment by abishekrsrikaanth** [comment] 2023-07-24 13:30
@zepfietje, this issue seems to occur to all components that also use the `live()` method. Should I create a separate issue for that? The same console error occurs.

**Comment by abishekrsrikaanth** [comment] 2023-07-24 13:44
I actually created another issue https://github.com/filamentphp/filament/issues/7182

**Comment by zepfietje** [comment] 2023-07-24 13:49
Aren't those 1 issue then?

**Comment by abishekrsrikaanth** [comment] 2023-07-24 13:51
Now that I look at it in more detail, any action that involves a server call is causing this issue. Clicking the `Next`, `Cancel`, `Submit` buttons have the same issue. How do you want me to document this on the issue?

**Comment by abishekrsrikaanth** [comment] 2023-07-24 14:04
At this point, creating an Action with the `steps` method is not usable at all as all server calls seem to throw the console error. Closed the other issue and updated the title of this one to make more sense of the issue.

**Comment by abishekrsrikaanth** [comment] 2023-07-24 15:42
@zepfietje after further testing, I can confirm that this issue is not with just using the `steps` method but also the `form` method on the Action class. Furthermore, I have isolated that this issue only happens when using the `Wizard` & `Step` components. Components added to the form of an `Action` work fine without the Wizard. I hope that help figuring out the cause of the issue.

**Comment by zepfietje** [comment] 2023-07-24 16:52
Might this be a duplicate of https://github.com/filamentphp/filament/issues/7064, @abishekrsrikaanth @danharrin?

**Comment by abishekrsrikaanth** [comment] 2023-07-24 18:46
@zepfietje @danharrin  I don't see this issue on a modal with Form Components but only when using the wizard. I tested the above scenarios with both the modal and the slideover and they seem to work well. Only when the wizard and steps are added to the modal or slideover does this issue occur.

**Comment by andgith** [comment] 2023-07-26 14:22
I'm seeing the same console error when using the wizard in a page.

Here is a simple reproduction:

```php
<?php

namespace App\Filament\Pages;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Wizard;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Form;
use Filament\Pages\Page;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\HtmlString;

class Import extends Page
{
    use InteractsWithForms;

    protected static ?string $navigationIcon = 'heroicon-m-document-text';

    protected static string $view = 'filament.pages.import';

    public $aaa;

    public $bbb;

    public $ccc;

    public function create()
    {
        return dd($this->form->getState());
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            Wizard::make([
                Wizard\Step::make('Order')
                    ->schema([
                        TextInput::make('aaa')
                    ]),
                Wizard\Step::make('Delivery')
                    ->schema([
                        // ...
                    ]),
                Wizard\Step::make('Billing')
                    ->schema([
                        // ...
                    ]),
            ])
        ]);
    }
}
```

### Package Version
v3.0.0.0-beta10

**Comment by awcodes** [comment] 2023-08-09 18:12
Weird question, did you require Livewire manually instead of letting Filament require it as a dependency?

I can't replicate this, in both the provided repo and the example given above on a custom page.

**Comment by abishekrsrikaanth** [comment] 2023-08-09 18:15
@awcodes , since the v3 release, this issue seems to have fixed itself. I think this can be closed.

**Comment by awcodes** [comment] 2023-08-09 18:15
Thank you.

**Closed as completed by awcodes** 2023-08-09 18:15 UTC
Labels: bug, unconfirmed, high priority
