### ISSUE TITLE
Markdown & Repeater Bugs

### ISSUE THREAD

**Issue by movicat** [laravel-filament/filament#9727] opened 2023-11-18 06:41 UTC
### Package

filament/filament

### Package Version

v3.0.97

### Laravel Version

v10.28.0

### Livewire Version

v3.0.8

### PHP Version

PHP 8.1.24

### Problem description

MarkdownEditor  - has problems displaying code and console errors.
Repeater - console errors

### Expected behavior

everything is clear

### Steps to reproduce

shown in video

https://github.com/filamentphp/filament/assets/36602392/8d016e88-26b3-4b50-baa8-1d2ad9ae71c0

https://github.com/filamentphp/filament/assets/36602392/6e8b835e-4543-4c74-9b5b-71b6a43a63c4

### Reproduction repository

https://github.com/movicat/filament-demo

**Comment by danharrin** [comment] 2023-11-18 13:05
These are unrelated issues, ideally they should have been put in separate issues.

Also, I don't think we are going to be able to fix the markdown editor, it's probably just a bug with EasyMDE.

**Comment by danharrin** [comment] 2023-11-18 13:06
Also, the console errors on the select are harmless and don't actually impact the functionality of the component?

**Comment by danharrin** [comment] 2023-12-11 10:29
I cannot reproduce exactly what you are typing into the markdown editor to get that behaviour.

The console errors are Livewire related and harmless to the functionality of the page, they will be fixed in due course.

**Closed as not planned by danharrin** 2023-12-11 10:29 UTC
Labels: bug, unconfirmed, low priority

**Comment by marcelosantos89** [comment] 2024-03-14 09:34
I got the same problem when using the spatie translatable. The functionality of the field stops working you can no longer select words and the cursor always shows at the start.
edit: I replaced it with a rich editor and this does not happen.
