### ISSUE TITLE
MarkdownEditor field not working when used as a dependent field

### ISSUE THREAD

**Issue by martinmildner** [laravel-filament/filament#562] opened 2021-09-04 22:09 UTC
### Package

filament/filament

### Package Version

v1.10.11

### Laravel Version

v8.58.0

### Livewire Version

v2.5.5

### PHP Version

PHP 8.0.9

### Bug description

When using a MarkdownEditor field as a dependent field, the editor is not loading correctly
<img width="877" alt="Bildschirmfoto 2021-09-04 um 22 54 02" src="https://user-images.githubusercontent.com/789541/132109151-96283715-05d1-499f-ada6-6a33db6cb3a1.png">

JS Error:
```
Alpine Error: "ReferenceError: Can't find variable: markdownEditor"
```

### Steps to reproduce

```php
BelongsToSelect::make('element_type_id')
    ->relationship('ElementType', 'title')
    ->preload()
    ->dependable(),
MarkdownEditor::make('text')
    ->when(fn ($record) => $record->element_type_id === 6)
```

**Comment by danharrin** [comment] 2021-09-04 22:15
It looks like there's a layout issue with the `Write` and `Preview` buttons - so unsure if this could be a general issue with your assets and not just Alpine?

**Comment by martinmildner** [comment] 2021-09-04 22:51
Checked it again - the error only happens when within modal edit view.

**Comment by danharrin** [comment] 2021-09-22 17:55
Out of interest, have you tried out the `filament/forms` package? It isn't compatible with `filament/filament` for another few months, but I'd like to know if the bug is still present. [Docs are here](https://filamentadmin.com/docs/forms).

**Comment by danharrin** [comment] 2021-11-14 17:00
Cannot reproduce in v2 so closing this. Feel free to submit a PR to the `1.x` branch if you'd still like a fix.

**Closed by danharrin** 2021-11-14 17:00 UTC
Labels: bug, unconfirmed
