### ISSUE TITLE
Dependent CheckboxList not working

### ISSUE THREAD

**Issue by nerdroid23** [laravel-filament/filament#9063] opened 2023-10-13 01:35 UTC
### Package

filament/filament

### Package Version

v3.0.73

### Laravel Version

v10.28.0

### Livewire Version

v3.0.8

### PHP Version

PHP 8.1.19

### Problem description

Hello, I have a  cities CheckboxList that depends on a states Select which also depends on a suppliers Select. Meaning that when I select one or more suppliers, the states select should display the states belongs to the selected suppliers, and when I select the states, the CheckboxList should show all the cities that belongs to the selected states.

The dependent suppliers and states Selects work just fine but I am having an issue with the cities CheckboxList, for some odd reason it is not displaying the results. It just displays the empty state message. I even added a dependent cities Select just to make sure that the relationships are correctly set up as it is shown in the video, they are. So I am not quite sure the reason why the cities CheckboxList isn't working.

### Expected behavior

The dependent CheckboxList should display the options returned by the query being executed.

### Steps to reproduce

See this short video for the reproduction steps

https://github.com/filamentphp/filament/assets/21242932/dd13679f-d88f-4cf4-a55d-4518dd64da6b

### Reproduction repository

https://github.com/nerdroid23/filament-checkboxlist-issue

**Comment by nerdroid23** [comment] 2023-10-13 01:40
I forgot to mention that when I remove `->searchable()` from the CheckboxList, it works partially, in the sense that the results are shown however the bulk select toggle doesn't work. The video below showcases this

https://github.com/filamentphp/filament/assets/21242932/a0df0067-eccf-47b8-899f-c72cfbe451b7

**Comment by zepfietje** [comment] 2023-10-13 06:37
Are there any console errors, @nerdroid23?

@danharrin, not too sure, but wasn't there an issue with Livewire and conditional Alpine components?

**Comment by nerdroid23** [comment] 2023-10-13 15:31
There are console errors however only when I type something in the search box. Example below

https://github.com/filamentphp/filament/assets/21242932/16972daf-3977-4f40-998d-f4cdf3393e39

<details>
<summary>and here's the log:</summary>

```
Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at [Alpine] 
                            $el
                                .querySelector('.fi-fo-checkbox-list-option-label')
                                .innerText.toLowerCase()
                                .includes(search.toLowerCase()) ||
                                $el
                                    .querySelector('.fi-fo-checkbox-list-option-description')
                                    .innerText.toLowerCase()
                                    .includes(search.toLowerCase())
                         (eval at safeAsyncFunction (http://localhost:8000/livewire/livewire.js?id=178de384:1281:21), <anonymous>:10:37)
    at http://localhost:8000/livewire/livewire.js?id=178de384:1303:23
    at tryCatch (http://localhost:8000/livewire/livewire.js?id=178de384:1223:14)
    at http://localhost:8000/livewire/livewire.js?id=178de384:3511:19
    at Array.reactiveEffect (http://localhost:8000/livewire/livewire.js?id=178de384:2388:18)
    at flushJobs (http://localhost:8000/livewire/livewire.js?id=178de384:764:15)
```

</details>

@zepfietje

**Comment by cheesegrits** [comment] 2023-10-13 15:40
@zepfietje 

Hey, I did some digging on this in the associated Discord #help thread, here's what I came up with:

I can see what's going wrong, but for the life of me can't figure out the fix.

The problem is on this line ...

https://github.com/filamentphp/filament/blob/3.x/packages/forms/resources/views/components/checkbox-list.blade.php#L148

... the x-show for the options.  Which, if searchable, checks to see if any options are currently visible with the current search string, and if not, hides them (and shows the "no records match your search" msg instead).

The problem is, the function that figure out which options should be visible relies on the main checkboxListOptions array, which is built in the x-init on line 14 from the options present in the DOM when the component is initialized.  But the x-init only runs once, when the component is first loaded, and of course there are no options on the DOM at that point, because the checkbox list is empty until the dependency gets met.  And x-init It doesn't run after Livewire updates.

So on line 37, after your dependent stuff kicks off a Livewire update and the Livewire.hook code runs, and re-runs updateVisibleCheckboxListOptions() ... it doesn't find any options, because the main checkboxListOptions is still empty.  So visibleCheckboxListOptions remains empty, and x-show remains hidden.

I tried half a dozen different ways to rebuild the checkboxListOptions array during the Livewire.hook code, but can't figure it out.

Can you submit an issue on the Filament Github, provbide this repo as your repro.  I'll summarize my findings there, and someone on the core team smarter than I am with Livewire can figure out the solution.

**Comment by zepfietje** [comment] 2023-10-13 16:44
Thanks, @cheesegrits!
Did you try rebuilding the `checkboxListOptions` array in the way it gets set initially?
I feel like replacing `this.checkboxListOptions` on line 72 with `Array.from($root.querySelectorAll('.fi-fo-checkbox-list-option-label'))` should work.

But maybe I'm missing something? 🙂

**Comment by cheesegrits** [comment] 2023-10-13 21:34
@zepfietje  I tried that, but at the time that code runs, the DOM doesn't seem to have been updated, and the querySelectorAll() finds nothing.

I tried changing the hook to morph.added or morph.updated, but that didn't work either.  Those new checkboxes just aren't in the DOM that I can find.

As I said, "I tried half a dozen different ways to rebuild the checkboxListOptions array during the Livewire.hook code".

**Comment by cheesegrits** [comment] 2023-10-13 23:35
I believe I may have a fix for this, after working on another seemingly unrelated issue.  PR incoming.

**Comment by cheesegrits** [comment] 2023-10-14 02:45
@nerdroid23 @zepfietje 

PR submitted.


https://github.com/filamentphp/filament/assets/934456/f4e4309c-8d49-43a1-9662-a9a31308f51f

**Comment by zepfietje** [comment] 2023-10-14 10:40
Thanks a lot, @cheesegrits! 🫶

**Closed as completed** 2023-10-14 11:11 UTC
Labels: bug, unconfirmed, low priority

**Comment by nerdroid23** [comment] 2023-10-14 12:46
Thanks @cheesegrits 🙏

**Comment by Zakaria010701** [comment] 2024-04-04 10:50
is someone active i have the same problem like him
