### ISSUE TITLE
Select searchable not working when started disabled

### ISSUE THREAD

**Issue by Giacomo-Gozzi** [laravel-filament/filament#8951] opened 2023-10-07 18:15 UTC
### Package

filament/filament

### Package Version

v3.0.69

### Laravel Version

10.26.2

### Livewire Version

v3.0.5

### PHP Version

v8.2.11

### Problem description

When the element started disabled and the state change to enabled by an live action on form the searchable element not working 

### Expected behavior

Expect that when the item return enabled is able to search results

### Steps to reproduce

- Create a form with 2 selection ( the second one is disable until the first have a valid item selected )
- Select an item on first selection
- Try to use second select and not working

### Reproduction repository

https://github.com/Giacomo-Gozzi/filament_select_issue.git

**Comment by andrewdwallo** [comment] 2023-10-07 19:40
Yeah, this has been an issue for a while now. It would be extremely helpful if this was fixed. 

To get this to work, we used to have to do something like this, which did work:
```php
Select::make('first')
        ->searchable()
        ->options([
            'element 1' => 1,
            'element 2' => 2,
            'element 3' => 3,
        ])
        ->live(),
Select::make('second')
        ->searchable(static fn(Select $component) => !$component->isDisabled())
        ->options([
            'element 1' => 1,
            'element 2' => 2,
            'element 3' => 3,
        ])
        ->dehydrated()
        ->disabled(static fn (Get $get): bool => $get('first') === null),
```

But this method hasn't been working for quite a while.

As of right now, as far as I know, in order to do the same thing, something similar to this is necessary:
```php
Select::make('first')
        ->searchable()
        ->options([
            'element 1' => 1,
            'element 2' => 2,
            'element 3' => 3,
        ])
        ->live(),
Select::make('second')
    ->label('Second')
    ->searchable()
    ->options([
        'element 1' => 1,
        'element 2' => 2,
        'element 3' => 3,
    ])
    ->hidden(static fn (Get $get): bool => blank($get('first'))),
Select::make('second_fake')
    ->label('Second')
    ->searchable()
    ->options([
        'element 1' => 1,
        'element 2' => 2,
        'element 3' => 3,
    ])
    ->hidden(static fn (Get $get): bool => filled($get('first')))
    ->disabled(static fn (Get $get): bool => blank($get('first'))),
```

@Giacomo-Gozzi You can do something similar to the above, until hopefully, this issue is able to be fixed.

**Comment by zepfietje** [comment] 2023-10-08 06:56
This has never worked, as it's a limitation with Choices.js.
Please search through existing issues before creating a bug report.

Closing as dupe of https://github.com/filamentphp/filament/issues/3068.
It's actually been reported already on the exact same day as this issue was: https://github.com/filamentphp/filament/issues/8935.

**Closed as not planned by zepfietje** 2023-10-08 06:56 UTC
Labels: bug, unconfirmed, low priority
