### ISSUE TITLE
When checkboxlist or select options with Enum :int  in form could not be remove.

### ISSUE THREAD

**Issue by wxfjamdc** [laravel-filament/filament#8423] opened 2023-09-12 06:44 UTC
### Package

filament/forms

### Package Version

v3.0.47

### Laravel Version

v10

### Livewire Version

 v3.0.2

### PHP Version

PHP 8.1

### Problem description

I used bitwise assignment on an int field and then created an enum class for this field.

Pass in the enumeration class in the option of the form's checkboxlist or select field.

The form can be created normally, but when modified, if you try to delete items in the checkboxlist or select, a type error will be prompted.

```
App\Enums\UserTypeEnum::from(): Argument #1 ($value) must be of type int, string given
```

### Expected behavior

Livewire does not pass the "__rm__ " value when modifying, or it can receive parameters normally.

### Steps to reproduce

![image](https://github.com/filamentphp/filament/assets/15729498/c9f6f843-c94d-4e91-a615-b6327b6179da)

![image](https://github.com/filamentphp/filament/assets/15729498/c17d77b6-96d3-4646-858c-ecc840fef8c8)

### Reproduction repository

https://github.com/wxfjamdc/filamentphp_form_with_enum

**Comment by danharrin** [comment] 2023-09-12 08:05
If you could help us by attempting a PR, that would be great!

**Comment by ilpav12** [comment] 2023-09-22 23:29
This is issue has been also mention here https://github.com/livewire/livewire/discussions/6801 on livewire repository

**Comment by zepfietje** [comment] 2023-09-25 13:30
So this is a Livewire issue?
If so, someone should attempt a failing test PR to the Livewire repo.
Otherwise it won't be fixed there.

**Comment by ilpav12** [comment] 2023-09-26 13:30
I don't know if it fixable from filament because the issue is how Livewire send updates. 
As can be seen in the livewire discussion the body is something like this:
```json
{
    "_token": "avu27UX1G0fNux3D1QGpH2XPAU1ofsdlMF6J3QfL",
    "components": [
        {
            "snapshot": "{...},\"checksum\":\"...\"}",
            "updates": {
                "note.topics.1": "__rm__"
            },
            "calls": []
        }
    ]
}
```
The Enum value is set to `"__rm__"` that triggers a wrong type exception.
I don't know it this behavior can be override.

**Comment by zepfietje** [comment] 2023-09-26 14:02
Okay, I'm going to close this as a Livewire issue then.
Unless @danharrin wants to keep it open for tracking.

**Closed as not planned by zepfietje** 2023-09-26 14:02 UTC
Labels: bug, unconfirmed, low priority

**Comment by johanmolen** [comment] 2023-12-17 20:09
Sorry for the late comment here, but does anyone know if this is getting fixed in Livewire? It does affect multiple Filament projects of mine.
