### ISSUE TITLE
KV field options order not persisted

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#9030] opened 2023-10-11 12:50 UTC
### Package

filament/filament

### Package Version

3.0.73

### Laravel Version

10.2.6

### Livewire Version

3.0.7

### PHP Version

8.2

### Problem description

When KV field options are re-ordered, the new order isn't saved to the database.

Video: https://www.youtube.com/watch?v=f1-cXpiawPY 

### Expected behavior

The new order should be persisted to the db.

### Steps to reproduce

Please see this video for reproduction steps: https://www.youtube.com/watch?v=f1-cXpiawPY

### Reproduction repository

https://github.com/binaryfire/filament-kv-bug

**Comment by danharrin** [comment] 2023-10-15 11:47
Unfortunately I think this is not an issue that Filament can solve. When Eloquent gets a JS object from the frontend with numeric keys, it will convert it to a PHP array, which will reorder the keys in numeric order. That then gets saved.

**Comment by binaryfire** [comment] 2023-10-15 11:57
@danharrin But this is happening with non-numeric keys too. See: https://www.youtube.com/watch?v=kXOtrJ61PIE. Are you able to reproduce this example?

`->reorderable()` doesn't seem to be working properly on KV fields in general (at least for me).

**Comment by danharrin** [comment] 2023-10-15 12:00
Alright, I would appreciate if you could investigate this further to see where the order is lost. But I wouldn't expect numeric keys to work, even if you fix the alphabetical ones.

**Comment by binaryfire** [comment] 2023-10-15 12:48
Unfortunately I wasn't able to figure this out. Hopefully someone more familiar with the KV field can take a look.

**Comment by danharrin** [comment] 2023-12-08 12:34
Here's the problem, with Livewire: https://wirebox.app/b/y8232

When reordering the keys of an object with `$entangle`, or setting the entire object, Livewire doesn't actually overwrite the old object, so the keys remain in the same order.

You can use the code in the Wirebox to create a failing test for the Livewire repository.

Since this is a confirmed issue with a dependency, I'm going to close this, as no action can be taken on our end. The resolution will come when Livewire fixes your failing test PR.

This will fix alpha keys, numeric keys are not fixable due to how JavaScript works.

**Comment by binaryfire** [comment] 2023-12-08 13:13
@danharrin Thanks for clarifying. You mentioned a failing PR test- has one already been submitted? I'd need help with that. I mostly write Selenium (e2e) tests and am not good with Pest / PHPUnit.

**Comment by danharrin** [comment] 2023-12-08 13:28
Unfortunately, I just don't have time to dedicate to that. I'm sure you could find someone else that can help you. At least you now know what the problem is now. Sorry.

**Comment by binaryfire** [comment] 2023-12-22 02:04
@danharrin Can we re-open this and mark it as help wanted? I opened a bug discussion 2 weeks ago in the Livewire repo asking for help and included the Wirebox link but didn't get any takers.

**Comment by ryangjchandler** [comment] 2023-12-26 19:49
@binaryfire If you're using MySQL and the `JSON` column type, it doesn't guarantee preservation of order with object keys. I'd recommend using `longText()` instead of `json()` for this exact reason.

**Comment by danharrin** [comment] 2023-12-26 19:50
@ryangjchandler thats also true, but there is a LW issue here as well with string-based key ordering

**Comment by ryangjchandler** [comment] 2023-12-26 19:51
Yeah, was just a suggestion, as I've not experience issues with LW string-based key ordering at all but always have problems with MySQL's JSON type.

**Comment by danharrin** [comment] 2023-12-26 20:02
There have been issues with it since LW3

**Comment by binaryfire** [comment] 2023-12-26 20:59
@ryangjchandler Yeah tried that but didn’t help. The issue seems to be caused by what Dan pointed out in this Wirebox: https://wirebox.app/b/y8232.

I don’t have any experience with browser tests in PHP so hoping someone can help write the failing test PR.

**Comment by binaryfire** [comment] 2024-01-05 01:30
Added failing test: https://github.com/livewire/livewire/pull/7671

**Closed as not planned** 2024-01-05 07:23 UTC
Labels: confirmed, bug in dependency, low priority, help wanted

**Comment by binaryfire** [comment] 2024-01-21 18:33
@danharrin FYI: https://github.com/livewire/livewire/pull/7671#issuecomment-1902719058

**Comment by danharrin** [comment] 2024-01-21 22:27
Thanks. Please double check that it fixes the issue, once Livewire gets its next release

**Comment by stuartcusackie** [comment] 2025-11-25 19:36
Just to add that this is an issue with JSON data in general. If I have two separate fields saving to the same column, e.g. TextInput('data.fieldX') and TextInput('data.fieldY') then there is no guarantee that the 'data' column will be saved in the original order and I am noticing differences in the way the data is saved between Windows and Linux machines. It's an unusual requirement for my app to preserve the json order as my Filament Form Schemas change a lot over time.

As mentioned above, using longText() instead of json() solves it but it can introduce data integrity, querying and performance issues. In my case these are all fine trade-offs, and actually Eloquent uses Doctrine DBAL to enable JSON-style querying on a longText column anyway.

The only other solution would be for Filament to change the way it saves JSON, so instead of:
```data: {'fieldX': 'a', 'fieldY': 'b'}```
it could be:
```data: {{'fieldX': 'a'}, {'fieldY': 'b'}}```

Though I'm neither sure if that's a good idea or even possible.  Just wanted to share what I learnt today 😁
