### ISSUE TITLE
Textarea should not pass submit on return

### ISSUE THREAD

**Issue by mischasigtermans** [laravel-filament/filament#12026] opened 2024-03-25 09:49 UTC
### Package

filament/forms

### Package Version

v3.2.54

### Laravel Version

v10.48.3

### Livewire Version

v3.4.9

### PHP Version

PHP 8.3.3

### Problem description

Currently textareas pass submit to the form on return.
![screenshot-001446 (2024-03-25)](https://github.com/filamentphp/filament/assets/22501510/e63f2869-1458-4f5f-b6b2-c3466eb2b956)

### Expected behavior

By default textareas should accept returns without submitting the form. More info on this [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement).

### Steps to reproduce

Add a textarea to any form, hit return. @danharrin you can try on the create appointment modal on Stagent, it has the description textarea. For other modals we added a temp. fix.

### Reproduction repository

https://github.com/getstagent/app

**Comment by zepfietje** [comment] 2024-03-26 09:40
Assigning to @danharrin as I can't access the reproduction repository.
Ideally provide an openly available repo, @mischasigtermans.

**Comment by mischasigtermans** [comment] 2024-03-26 10:16
It's as easy as adding a textarea to any form to reproduce tho.

**Comment by zepfietje** [comment] 2024-03-26 10:25
> It's as easy as adding a textarea to any form to reproduce tho.

Nope it's not, I can't reproduce it.

**Comment by dissto** [comment] 2024-03-26 12:21
> > It's as easy as adding a textarea to any form to reproduce tho.
> 
> Nope it's not, I can't reproduce it.



https://github.com/filamentphp/filament/assets/11778632/4653a51a-c49f-43b0-a461-0b6e52eb6d05


I am also not able to reproduce it

**Comment by zepfietje** [comment] 2024-03-26 21:38
Thanks for double-checking, @dissto.
Closing this until a public reproduction repository is provided.

**Closed as not planned by zepfietje** 2024-03-26 21:38 UTC
Labels: bug, unconfirmed, low priority
