### ISSUE TITLE
Required checkbox inside modal wizard

### ISSUE THREAD

**Issue by OpJePl44tsm4n** [laravel-filament/filament#13816] opened 2024-08-05 11:30 UTC
### Package

filament/filament

### Package Version

v3.2.85

### Laravel Version

v11.9.2

### Livewire Version

v3.5.0

### PHP Version

8.2

### Problem description

When adding a required checkbox to a modal wizard, the field won't get validated. 

### Expected behavior

the checkbox should return a validation error. (this works in a modal without a wizard)

### Steps to reproduce

- add an action like described in [using-a-wizard-as-a-modal-form](https://filamentphp.com/docs/3.x/actions/modals#using-a-wizard-as-a-modal-form). 
- add required Checkbox field 
- steps won't validate the field

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/OpJePl44tsm4n/filament-wizard-bug

**Comment by zepfietje** [comment] 2024-08-06 07:30
This is caused by client-side validation not being executed (to fix issues in wizards).
Checkboxes should use `accepted()` instead of `required()` for back-end validation.
I'm wondering if we should apply `accepted` validation when using `required()` with a checkbox, @danharrin?

**Comment by zepfietje** [comment] 2024-08-06 07:31
For now you may work around the issue by using `accepted()`, @OpJePl44tsm4n.

**Comment by zepfietje** [comment] 2024-08-06 07:32
Given what I said above, I don't think this classifies as a bug actually.
I'm going to close this issue, but we may introduce improvements as I suggested in my first comment.

**Closed as not planned by zepfietje** 2024-08-06 07:32 UTC
Labels: bug, confirmed, medium priority

**Comment by danharrin** [comment] 2024-08-07 10:38
required is checking the value is not null, whereas accepted checks if it is true, we shouldnt apply both by default
