### ISSUE TITLE
Duplicate requests when removing entangled filters

### ISSUE THREAD

**Issue by archilex** [laravel-filament/filament#8077] opened 2023-08-25 19:56 UTC
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.2

### Problem description

If

1. you combine two or more filters on your table and
2. at least one of those filters has is $entangled (ie. adding `searchable()` to a select, adding `toggle()` to a filter, or using a date filter with `native(false)`) 

then when you remove one of the other filters the component will be rendered twice and therefore your table query will also happen twice. 

I'm pretty sure this is related to the current issue with LW entangled. However, interestingly, the toggle() component while it does use `$entangled`, does NOT use `$watch`...So it might only be related to `entangled` and not `$watch`.

I'm documenting this here hoping it'll help give insight into the overall problem with LW and $entangled.

Here's a video showing the issue

The first pass is with no entangled filters. Watch debug bar and you'll see just one request per removed filter.
The second is with a different toggled() applied to the filter. You'll now see duplicate requests in LW when removing the other filters. 
(The video was longer with demos of the other filters exhibiting the same issue, but the file size was too large to upload)

https://github.com/filamentphp/filament/assets/6097099/24c383db-da7d-4807-9c86-8ca62e3a3c2a

### Expected behavior

Removing entangled filters should only trigger one request.

### Steps to reproduce

1. Add a filter that doesn't use entangled (like a filter with a form input on it)
2. Add another filter that does use entangled (like a checkbox filter that has the `toggle()` method on it)
3. Apply both filters to the table
4. Remove the non-entanlged filter and watch debugbar for 2 requests.

### Reproduction repository

https://github.com/archilex/demo/tree/duplicate-query-with-filter-demo

**Comment by archilex** [comment] 2023-08-25 20:22
And if you're wondering, you can ignore the duplicate queries warning that debugbar shows at the bottom. That's due to the select filter querying the users to build the select options. The issue still occurs even without the select.

**Comment by archilex** [comment] 2023-08-26 16:37
Hopefully this is related to all the other LW/Alpine issues like #7940 and others. I submitted a failing test for this at Livewire that will hopefully help them as they look into the problem.

**Comment by danharrin** [comment] 2023-09-10 23:17
I think this is a LW issue, so closing this. We can reopen if the issue is on the Filament side.

**Closed as not planned by danharrin** 2023-09-10 23:17 UTC
Labels: bug, unconfirmed
