### ISSUE TITLE
Tabbing to searchable select input adds arrow text 

### ISSUE THREAD

**Issue by jameshine** [laravel-filament/filament#5989] opened 2023-03-21 20:18 UTC
### Package

filament/filament

### Package Version

v2.17.17

### Laravel Version

v10.4.1

### PHP Version

PHP 8.2.2

### Problem description

https://user-images.githubusercontent.com/888834/226725314-5a4b74ba-2d18-4a4f-b265-e6191e5d4906.mov

Apologies for the poorly named title. I've got a select input that is searchable. Tabbing from a previous field into the select and hitting the up or down arrow adds "arrowdown"/"arrowup" respectively. If you hit ESC and then press an arrow key again, it'll append the previous text.

### Expected behavior

Not to display the text or not to duplicate the text each time.

### Steps to reproduce

1. Login (test@email.com / password)
2. Visit admin/users/create
3. Focus name input
4. Press tab
5. Press up or down arrow (see text)
6. Press ESC
7. Press up or down arrow (see repeated text).

### Reproduction repository

https://github.com/jameshine/filament-searchable-select-bug

**Comment by danharrin** [comment] 2023-03-25 16:28
Very weird. Sure this isn't a Choices.js bug?

**Comment by zepfietje** [comment] 2023-03-25 21:25
Duplicate of https://github.com/filamentphp/filament/issues/5924?

**Comment by danharrin** [comment] 2023-03-25 21:44
Don't think so

**Comment by zepfietje** [comment] 2023-03-27 12:11
Pretty sure it is. Check https://filament-bug.jordanwelch.com.

**Comment by zepfietje** [comment] 2023-03-27 12:12
Reopen if you think I'm wrong. 👍

**Closed as not planned** 2023-03-27 12:11 UTC
Labels: bug, confirmed, bug in dependency

**Comment by danharrin** [comment] 2023-03-27 12:50
Fair, it can also be replicated there. Not sure if the issue author originally intended it to be used for this problem too though

**Comment by zepfietje** [comment] 2023-03-27 12:52
To me it seemed like the original issue report was this exact problem.

**Comment by danharrin** [comment] 2023-03-27 13:09
The original issue is to point out that the search doesn't work immediately after focusing. Not the `arrowright` text stuff

**Comment by danharrin** [comment] 2023-03-27 13:12
Actually, this particular issue is present in Choices.js itself, it's not a Filament issue.

https://choices-js.github.io/Choices/

Tab to the "Default" "Single select input" and then press the right arrow

**Comment by zepfietje** [comment] 2023-04-11 08:08
You were right, @danharrin.
I mistakenly thought this was the exact same as linked issue.
However, they do all seem to be related to a bug in Choices.js.
