### ISSUE TITLE
Hidden wizard steps are focusable

### ISSUE THREAD

**Issue by izzudin96** [laravel-filament/filament#13127] opened 2024-06-06 23:29 UTC
### Package

filament/filament

### Package Version

v3.2.85

### Laravel Version

10.48.12

### Livewire Version

v3.5.0

### PHP Version

8.1.26

### Problem description

When using the Filament Wizard in accessibility mode or when navigating with the keyboard (tabbing), the form fields on the first step tab into the hidden fields of the second step instead of moving to the "Next" button. This behavior disrupts the form-filling process and impacts the accessibility and usability of the wizard.

Note: This issue does not occur in version v3.2.63; the tabbing functionality works as expected in that version.

### Expected behavior

When filling out the forms in the first step of the wizard, tabbing should sequentially move through all the form fields and then to the "Next" button. Only after clicking the "Next" button should the focus move to the fields in the second step.

### Steps to reproduce

1. Activate accessibility mode or navigate using the keyboard (tab key).
2. Fill out any form fields in the first step of the Filament Wizard.
3. Observe that tabbing skips to the hidden fields in the second step instead of the "Next" button.
4. Notice that the second step fields are tab-accessible even though they are not visible.

![image](https://github.com/filamentphp/filament/assets/34004451/fcbb4300-d46b-4985-ba97-00a745f0ad2f)

### Reproduction repository

https://github.com/izzudin96/filament-a11y

**Comment by izzudin96** [comment] 2024-06-07 00:03
Link to wizard: https://github.com/izzudin96/filament-a11y/blob/0c5ca9f54aaed9a945f61300f950858f44763929/app/Filament/Resources/PatientResource.php#L26C12-L27C6

**Comment by zepfietje** [comment] 2024-06-08 10:15
Might this be related to https://github.com/filamentphp/filament/pull/12985 (@sebapastore)?

Could you check if this issue occurs in Filament v3.2.84 too, @izzudin96?

**Comment by izzudin96** [comment] 2024-06-08 10:42
Hi @zepfietje,

Thanks for the reply.

I had a quick look on version `3.2.84` and it seems like it is working as expected.

<img width="1019" alt="image" src="https://github.com/filamentphp/filament/assets/34004451/9ac2920d-8c79-4554-a416-601cabce50c8">

**Comment by zepfietje** [comment] 2024-06-08 10:55
Thanks for checking, @izzudin96!

This confirms this bug is caused by the changes in https://github.com/filamentphp/filament/pull/12985. Marking this as high priority.
CC @danharrin @sebapastore

**Comment by sebapastore** [comment] 2024-06-08 14:05
I will look into it now!

**Closed as completed** 2024-06-09 08:28 UTC
Labels: bug, confirmed, high priority
